import 'dart:core';

import 'package:collection/collection.dart';
import 'package:gc_wizard/tools/science_and_technology/colors/logic/colors_rgb.dart';

class XKCDColor {
  final String colorcode;
  final String name;

  const XKCDColor({
    required this.colorcode,
    required this.name,
  });
}

const Map<String, XKCDColor> XKCD_COLOR_CODES = {
  'cloudy-blue': XKCDColor(colorcode: '#acc2d9', name: 'cloudy blue'),
 	'dark-pastel-green': XKCDColor(colorcode: '#56ae57', name: 'dark pastel green'),
 	'dust': XKCDColor(colorcode: '#b2996e', name: 'dust'),
 	'electric-lime': XKCDColor(colorcode: '#a8ff04', name: 'electric lime'),
 	'fresh-green': XKCDColor(colorcode: '#69d84f', name: 'fresh green'),
 	'light-eggplant': XKCDColor(colorcode: '#894585', name: 'light eggplant'),
 	'nasty-green': XKCDColor(colorcode: '#70b23f', name: 'nasty green'),
 	'really-light-blue': XKCDColor(colorcode: '#d4ffff', name: 'really light blue'),
 	'tea': XKCDColor(colorcode: '#65ab7c', name: 'tea'),
 	'warm-purple': XKCDColor(colorcode: '#952e8f', name: 'warm purple'),
 	'yellowish-tan': XKCDColor(colorcode: '#fcfc81', name: 'yellowish tan'),
 	'cement': XKCDColor(colorcode: '#a5a391', name: 'cement'),
 	'dark-grass-green': XKCDColor(colorcode: '#388004', name: 'dark grass green'),
 	'dusty-teal': XKCDColor(colorcode: '#4c9085', name: 'dusty teal'),
 	'grey-teal': XKCDColor(colorcode: '#5e9b8a', name: 'grey teal'),
 	'macaroni-and-cheese': XKCDColor(colorcode: '#efb435', name: 'macaroni and cheese'),
 	'pinkish-tan': XKCDColor(colorcode: '#d99b82', name: ''),
 	'spruce': XKCDColor(colorcode: '#0a5f38', name: ''),
 	'strong-blue': XKCDColor(colorcode: '#0c06f7', name: ''),
 	'toxic-green': XKCDColor(colorcode: '#61de2a', name: ''),
 	'windows-blue': XKCDColor(colorcode: '#3778bf', name: ''),
 	'blue-blue': XKCDColor(colorcode: '#2242c7', name: ''),
 	'blue-with-a-hint-of-purple': XKCDColor(colorcode: '#533cc6', name: ''),
 	'booger': XKCDColor(colorcode: '#9bb53c', name: ''),
 	'bright-sea-green': XKCDColor(colorcode: '#05ffa6', name: ''),
 	'dark-green-blue': XKCDColor(colorcode: '#1f635', name: ''),
 	'deep-turquoise': XKCDColor(colorcode: '#01737', name: ''),
 	'green-teal': XKCDColor(colorcode: '#0cb57', name: ''),
 	'strong-pink': XKCDColor(colorcode: '#ff078', name: ''),
 	'bland': XKCDColor(colorcode: '#afa88', name: ''),
 	'deep-aqua': XKCDColor(colorcode: '#08787', name: ''),
 	'lavender-pink': XKCDColor(colorcode: '#dd85d', name: ''),
 	'light-moss-green': XKCDColor(colorcode: '#a6c87', name: ''),
 	'light-seafoam-green': XKCDColor(colorcode: '#a7ffb', name: ''),
 	'olive-yellow': XKCDColor(colorcode: '#c2b70', name: ''),
 	'pig-pink': XKCDColor(colorcode: '#e78ea', name: ''),
 	'deep-lilac': XKCDColor(colorcode: '#966ebd;
 	'desert': XKCDColor(colorcode: '#ccad6', name: ''),
 	'dusty-lavender': XKCDColor(colorcode: '#ac86a', name: ''),
 	'purpley-grey': XKCDColor(colorcode: '#947e9', name: ''),
 	'purply': XKCDColor(colorcode: '#983fb', name: ''),
 	'candy-pink': XKCDColor(colorcode: '#ff63e', name: ''),
 	'light-pastel-green': XKCDColor(colorcode: '#b2fba', name: ''),
 	'boring-green': XKCDColor(colorcode: '#63b36', name: ''),
 	'kiwi-green': XKCDColor(colorcode: '#8ee53', name: ''),
 	'light-grey-green': XKCDColor(colorcode: '#b7e1a', name: ''),
 	'orange-pink': XKCDColor(colorcode: '#ff6f5', name: ''),
 	'tea-green': XKCDColor(colorcode: '#bdf8a', name: ''),
 	'very-light-brown': XKCDColor(colorcode: '#d3b68', name: ''),
 	'egg-shell': XKCDColor(colorcode: '#fffcc', name: ''),
 	'eggplant-purple': XKCDColor(colorcode: '#43054', name: ''),
 	'powder-pink': XKCDColor(colorcode: '#ffb2d', name: ''),
 	'reddish-grey': XKCDColor(colorcode: '#99757', name: ''),
 	'baby-shit-brown': XKCDColor(colorcode: '#ad900d;
 	'liliac': XKCDColor(colorcode: '#c48efd;
 	'stormy-blue': XKCDColor(colorcode: '#507b9', name: ''),
 	'ugly-brown': XKCDColor(colorcode: '#7d710', name: ''),
 	'custard': XKCDColor(colorcode: '#fffd7', name: ''),
 	'darkish-pink': XKCDColor(colorcode: '#da467d;
 	'deep-brown': XKCDColor(colorcode: '#41020', name: ''),
 	'greenish-beige': XKCDColor(colorcode: '#c9d17', name: ''),
 	'manilla': XKCDColor(colorcode: '#fffa8', name: ''),
 	'off-blue': XKCDColor(colorcode: '#5684a', name: ''),
 	'battleship-grey': XKCDColor(colorcode: '#6b7c8', name: ''),
 	'browny-green': XKCDColor(colorcode: '#6f6c0', name: ''),
 	'bruise': XKCDColor(colorcode: '#7e407', name: ''),
 	'kelley-green': XKCDColor(colorcode: '#00933', name: ''),
 	'sickly-yellow': XKCDColor(colorcode: '#d0e42', name: ''),
 	'sunny-yellow': XKCDColor(colorcode: '#fff91', name: ''),
 	'azul': XKCDColor(colorcode: '#1d5de', name: ''),
 	'darkgreen': XKCDColor(colorcode: '#05490', name: ''),
 	'green-slash-yellow': XKCDColor(colorcode: '#b5ce0', name: ''),
 	'lichen': XKCDColor(colorcode: '#8fb67', name: ''),
 	'light-light-green': XKCDColor(colorcode: '#c8ffb', name: ''),
 	'pale-gold': XKCDColor(colorcode: '#fdde6', name: ''),
 	'sun-yellow': XKCDColor(colorcode: '#ffdf2', name: ''),
 	'tan-green': XKCDColor(colorcode: '#a9be7', name: ''),
 	'burple': XKCDColor(colorcode: '#6832e', name: ''),
 	'butterscotch': XKCDColor(colorcode: '#fdb14', name: ''),
 	'toupe': XKCDColor(colorcode: '#c7ac7d;
 	'dark-cream': XKCDColor(colorcode: '#fff39', name: ''),
 	'indian-red': XKCDColor(colorcode: '#850e0', name: ''),
 	'light-lavendar': XKCDColor(colorcode: '#efc0f', name: ''),
 	'poison-green': XKCDColor(colorcode: '#40fd1', name: ''),
 	'baby-puke-green': XKCDColor(colorcode: '#b6c40', name: ''),
 	'bright-yellow-green': XKCDColor(colorcode: '#9dff0', name: ''),
 	'charcoal-grey': XKCDColor(colorcode: '#3c414', name: ''),
 	'squash': XKCDColor(colorcode: '#f2ab1', name: ''),
 	'cinnamon': XKCDColor(colorcode: '#ac4f0', name: ''),
 	'light-pea-green': XKCDColor(colorcode: '#c4fe8', name: ''),
 	'radioactive-green': XKCDColor(colorcode: '#2cfa1', name: ''),
 	'raw-sienna': XKCDColor(colorcode: '#9a620', name: ''),
 	'baby-purple': XKCDColor(colorcode: '#ca9bf', name: ''),
 	'cocoa': XKCDColor(colorcode: '#875f4', name: ''),
 	'light-royal-blue': XKCDColor(colorcode: '#3a2ef', name: ''),
 	'orangeish': XKCDColor(colorcode: '#fd8d4', name: ''),
 	'rust-brown': XKCDColor(colorcode: '#8b310', name: ''),
 	'sand-brown': XKCDColor(colorcode: '#cba56', name: ''),
 	'swamp': XKCDColor(colorcode: '#69833', name: ''),
 	'tealish-green': XKCDColor(colorcode: '#0cdc7', name: ''),
 	'burnt-siena': XKCDColor(colorcode: '#b7520', name: ''),
 	'camo': XKCDColor(colorcode: '#7f8f4', name: ''),
 	'dusk-blue': XKCDColor(colorcode: '#26538d;
 	'fern': XKCDColor(colorcode: '#63a95', name: ''),
 	'old-rose': XKCDColor(colorcode: '#c87f8', name: ''),
 	'pale-light-green': XKCDColor(colorcode: '#b1fc9', name: ''),
 	'peachy-pink': XKCDColor(colorcode: '#ff9a8', name: ''),
 	'rosy-pink': XKCDColor(colorcode: '#f6688', name: ''),
 	'light-bluish-green': XKCDColor(colorcode: '#76fda', name: ''),
 	'light-bright-green': XKCDColor(colorcode: '#53fe5', name: ''),
 	'light-neon-green': XKCDColor(colorcode: '#4efd5', name: ''),
 	'light-seafoam': XKCDColor(colorcode: '#a0feb', name: ''),
 	'tiffany-blue': XKCDColor(colorcode: '#7bf2d', name: ''),
 	'washed-out-green': XKCDColor(colorcode: '#bcf5a', name: ''),
 	'browny-orange': XKCDColor(colorcode: '#ca6b0', name: ''),
 	'nice-blue': XKCDColor(colorcode: '#107ab', name: ''),
 	'sapphire': XKCDColor(colorcode: '#2138a', name: ''),
 	'greyish-teal': XKCDColor(colorcode: '#719f9', name: ''),
 	'orangey-yellow': XKCDColor(colorcode: '#fdb91', name: ''),
 	'parchment': XKCDColor(colorcode: '#fefca', name: ''),
 	'straw': XKCDColor(colorcode: '#fcf67', name: ''),
 	'very-dark-brown': XKCDColor(colorcode: '#1d020', name: ''),
 	'terracota': XKCDColor(colorcode: '#cb684', name: ''),
 	'ugly-blue': XKCDColor(colorcode: '#31668', name: ''),
 	'clear-blue': XKCDColor(colorcode: '#247afd;
 	'creme': XKCDColor(colorcode: '#ffffb', name: ''),
 	'foam-green': XKCDColor(colorcode: '#90fda', name: ''),
 	'grey-slash-green': XKCDColor(colorcode: '#86a17d;
 	'light-gold': XKCDColor(colorcode: '#fddc5', name: ''),
 	'seafoam-blue': XKCDColor(colorcode: '#78d1b', name: ''),
 	'topaz': XKCDColor(colorcode: '#13bba', name: ''),
 	'violet-pink': XKCDColor(colorcode: '#fb5ff', name: ''),
 	'wintergreen': XKCDColor(colorcode: '#20f98', name: ''),
 	'yellow-tan': XKCDColor(colorcode: '#ffe36', name: ''),
 	'dark-fuchsia': XKCDColor(colorcode: '#9d075', name: ''),
 	'indigo-blue': XKCDColor(colorcode: '#3a18b', name: ''),
 	'light-yellowish-green': XKCDColor(colorcode: '#c2ff8', name: ''),
 	'pale-magenta': XKCDColor(colorcode: '#d767ad;
 	'rich-purple': XKCDColor(colorcode: '#72005', name: ''),
 	'sunflower-yellow': XKCDColor(colorcode: '#ffda0', name: ''),
 	'green-slash-blue': XKCDColor(colorcode: '#01c08d;
 	'leather': XKCDColor(colorcode: '#ac743', name: ''),
 	'racing-green': XKCDColor(colorcode: '#01460', name: ''),
 	'vivid-purple': XKCDColor(colorcode: '#9900f', name: ''),
 	'dark-royal-blue': XKCDColor(colorcode: '#02066', name: ''),
 	'hazel': XKCDColor(colorcode: '#8e761', name: ''),
 	'muted-pink': XKCDColor(colorcode: '#d1768', name: ''),
 	'booger-green': XKCDColor(colorcode: '#96b40', name: ''),
 	'canary': XKCDColor(colorcode: '#fdff6', name: ''),
 	'cool-grey': XKCDColor(colorcode: '#95a3a', name: ''),
 	'dark-taupe': XKCDColor(colorcode: '#7f684', name: ''),
 	'darkish-purple': XKCDColor(colorcode: '#75197', name: ''),
 	'true-green': XKCDColor(colorcode: '#08940', name: ''),
 	'coral-pink': XKCDColor(colorcode: '#ff616', name: ''),
 	'dark-sage': XKCDColor(colorcode: '#59855', name: ''),
 	'dark-slate-blue': XKCDColor(colorcode: '#21476', name: ''),
 	'flat-blue': XKCDColor(colorcode: '#3c73a', name: ''),
 	'mushroom': XKCDColor(colorcode: '#ba9e8', name: ''),
 	'rich-blue': XKCDColor(colorcode: '#021bf', name: ''),
 	'dirty-purple': XKCDColor(colorcode: '#734a6', name: ''),
 	'greenblue': XKCDColor(colorcode: '#23c48', name: ''),
 	'icky-green': XKCDColor(colorcode: '#8fae2', name: ''),
 	'light-khaki': XKCDColor(colorcode: '#e6f2a', name: ''),
 	'warm-blue': XKCDColor(colorcode: '#4b57d', name: ''),
 	'dark-hot-pink': XKCDColor(colorcode: '#d9016', name: ''),
 	'deep-sea-blue': XKCDColor(colorcode: '#01548', name: ''),
 	'carmine': XKCDColor(colorcode: '#9d021', name: ''),
 	'dark-yellow-green': XKCDColor(colorcode: '#728f0', name: ''),
 	'pale-peach': XKCDColor(colorcode: '#ffe5ad;
 	'plum-purple': XKCDColor(colorcode: '#4e055', name: ''),
 	'golden-rod': XKCDColor(colorcode: '#f9bc0', name: ''),
 	'neon-red': XKCDColor(colorcode: '#ff073', name: ''),
 	'old-pink': XKCDColor(colorcode: '#c7798', name: ''),
 	'very-pale-blue': XKCDColor(colorcode: '#d6fff', name: ''),
 	'blood-orange': XKCDColor(colorcode: '#fe4b0', name: ''),
 	'grapefruit': XKCDColor(colorcode: '#fd595', name: ''),
 	'sand-yellow': XKCDColor(colorcode: '#fce16', name: ''),
 	'clay-brown': XKCDColor(colorcode: '#b2713d;
 	'dark-blue-grey': XKCDColor(colorcode: '#1f3b4d;
 	'flat-green': XKCDColor(colorcode: '#699d4', name: ''),
 	'light-green-blue': XKCDColor(colorcode: '#56fca', name: ''),
 	'warm-pink': XKCDColor(colorcode: '#fb558', name: ''),
 	'dodger-blue': XKCDColor(colorcode: '#3e82f', name: ''),
 	'gross-green': XKCDColor(colorcode: '#a0bf1', name: ''),
 	'ice': XKCDColor(colorcode: '#d6fff', name: ''),
 	'metallic-blue': XKCDColor(colorcode: '#4f738', name: ''),
 	'pale-salmon': XKCDColor(colorcode: '#ffb19', name: ''),
 	'sap-green': XKCDColor(colorcode: '#5c8b1', name: ''),
 	'algae': XKCDColor(colorcode: '#54ac6', name: ''),
 	'bluey-grey': XKCDColor(colorcode: '#89a0b', name: ''),
 	'greeny-grey': XKCDColor(colorcode: '#7ea07', name: ''),
 	'highlighter-green': XKCDColor(colorcode: '#1bfc0', name: ''),
 	'light-light-blue': XKCDColor(colorcode: '#cafff', name: ''),
 	'light-mint': XKCDColor(colorcode: '#b6ffb', name: ''),
 	'raw-umber': XKCDColor(colorcode: '#a75e0', name: ''),
 	'vivid-blue': XKCDColor(colorcode: '#152ef', name: ''),
 	'deep-lavender': XKCDColor(colorcode: '#8d5eb', name: ''),
 	'dull-teal': XKCDColor(colorcode: '#5f9e8', name: ''),
 	'light-greenish-blue': XKCDColor(colorcode: '#63f7b', name: ''),
 	'mud-green': XKCDColor(colorcode: '#60660', name: ''),
 	'pinky': XKCDColor(colorcode: '#fc86a', name: ''),
 	'red-wine': XKCDColor(colorcode: '#8c003', name: ''),
 	'shit-green': XKCDColor(colorcode: '#75800', name: ''),
 	'tan-brown': XKCDColor(colorcode: '#ab7e4', name: ''),
 	'darkblue': XKCDColor(colorcode: '#03076', name: ''),
 	'rosa': XKCDColor(colorcode: '#fe86a', name: ''),
 	'lipstick': XKCDColor(colorcode: '#d5174', name: ''),
 	'pale-mauve': XKCDColor(colorcode: '#fed0f', name: ''),
 	'claret': XKCDColor(colorcode: '#68001', name: ''),
 	'dandelion': XKCDColor(colorcode: '#fedf0', name: ''),
 	'orangered': XKCDColor(colorcode: '#fe420', name: ''),
 	'poop-green': XKCDColor(colorcode: '#6f7c0', name: ''),
 	'ruby': XKCDColor(colorcode: '#ca014', name: ''),
 	'dark': XKCDColor(colorcode: '#1b243', name: ''),
 	'greenish-turquoise': XKCDColor(colorcode: '#00fbb', name: ''),
 	'pastel-red': XKCDColor(colorcode: '#db585', name: ''),
 	'piss-yellow': XKCDColor(colorcode: '#ddd61', name: ''),
 	'bright-cyan': XKCDColor(colorcode: '#41fdf', name: ''),
 	'dark-coral': XKCDColor(colorcode: '#cf524', name: ''),
 	'algae-green': XKCDColor(colorcode: '#21c36', name: ''),
 	'darkish-red': XKCDColor(colorcode: '#a9030', name: ''),
 	'reddy-brown': XKCDColor(colorcode: '#6e100', name: ''),
 	'blush-pink': XKCDColor(colorcode: '#fe828', name: ''),
 	'camouflage-green': XKCDColor(colorcode: '#4b611', name: ''),
 	'lawn-green': XKCDColor(colorcode: '#4da40', name: ''),
 	'putty': XKCDColor(colorcode: '#beae8', name: ''),
 	'vibrant-blue': XKCDColor(colorcode: '#0339f', name: ''),
 	'dark-sand': XKCDColor(colorcode: '#a88f5', name: ''),
 	'purple-slash-blue': XKCDColor(colorcode: '#5d21d', name: ''),
 	'saffron': XKCDColor(colorcode: '#feb20', name: ''),
 	'twilight': XKCDColor(colorcode: '#4e518', name: ''),
 	'warm-brown': XKCDColor(colorcode: '#964e0', name: ''),
 	'bluegrey': XKCDColor(colorcode: '#85a3b', name: ''),
 	'bubble-gum-pink': XKCDColor(colorcode: '#ff69a', name: ''),
 	'duck-egg-blue': XKCDColor(colorcode: '#c3fbf', name: ''),
 	'greenish-cyan': XKCDColor(colorcode: '#2afeb', name: ''),
 	'petrol': XKCDColor(colorcode: '#005f6', name: ''),
 	'royal': XKCDColor(colorcode: '#0c179', name: ''),
 	'butter': XKCDColor(colorcode: '#ffff8', name: ''),
 	'dusty-orange': XKCDColor(colorcode: '#f0833', name: ''),
 	'off-yellow': XKCDColor(colorcode: '#f1f33', name: ''),
 	'pale-olive-green': XKCDColor(colorcode: '#b1d27', name: ''),
 	'orangish': XKCDColor(colorcode: '#fc824', name: ''),
 	'leaf': XKCDColor(colorcode: '#71aa3', name: ''),
 	'light-blue-grey': XKCDColor(colorcode: '#b7c9e', name: ''),
 	'dried-blood': XKCDColor(colorcode: '#4b010', name: ''),
 	'lightish-purple': XKCDColor(colorcode: '#a552e', name: ''),
 	'rusty-red': XKCDColor(colorcode: '#af2f0d;
 	'lavender-blue': XKCDColor(colorcode: '#8b88f', name: ''),
 	'light-grass-green': XKCDColor(colorcode: '#9af76', name: ''),
 	'light-mint-green': XKCDColor(colorcode: '#a6fbb', name: ''),
 	'sunflower': XKCDColor(colorcode: '#ffc51', name: ''),
 	'velvet': XKCDColor(colorcode: '#75085', name: ''),
 	'brick-orange': XKCDColor(colorcode: '#c14a0', name: ''),
 	'lightish-red': XKCDColor(colorcode: '#fe2f4', name: ''),
 	'pure-blue': XKCDColor(colorcode: '#0203e', name: ''),
 	'twilight-blue': XKCDColor(colorcode: '#0a437', name: ''),
 	'violet-red': XKCDColor(colorcode: '#a5005', name: ''),
 	'yellowy-brown': XKCDColor(colorcode: '#ae8b0', name: ''),
 	'carnation': XKCDColor(colorcode: '#fd798', name: ''),
 	'muddy-yellow': XKCDColor(colorcode: '#bfac0', name: ''),
 	'dark-seafoam-green': XKCDColor(colorcode: '#3eaf7', name: ''),
 	'deep-rose': XKCDColor(colorcode: '#c7476', name: ''),
 	'dusty-red': XKCDColor(colorcode: '#b9484', name: ''),
 	'grey-slash-blue': XKCDColor(colorcode: '#647d8', name: ''),
 	'lemon-lime': XKCDColor(colorcode: '#bffe2', name: ''),
 	'purple-slash-pink': XKCDColor(colorcode: '#d725d', name: ''),
 	'brown-yellow': XKCDColor(colorcode: '#b2970', name: ''),
 	'purple-brown': XKCDColor(colorcode: '#673a3', name: ''),
 	'wisteria': XKCDColor(colorcode: '#a87dc', name: ''),
 	'banana-yellow': XKCDColor(colorcode: '#fafe4', name: ''),
 	'lipstick-red': XKCDColor(colorcode: '#c0022', name: ''),
 	'water-blue': XKCDColor(colorcode: '#0e87c', name: ''),
 	'brown-grey': XKCDColor(colorcode: '#8d846', name: ''),
 	'vibrant-purple': XKCDColor(colorcode: '#ad03d', name: ''),
 	'baby-green': XKCDColor(colorcode: '#8cff9', name: ''),
 	'barf-green': XKCDColor(colorcode: '#94ac0', name: ''),
 	'eggshell-blue': XKCDColor(colorcode: '#c4fff', name: ''),
 	'sandy-yellow': XKCDColor(colorcode: '#fdee7', name: ''),
 	'cool-green': XKCDColor(colorcode: '#33b86', name: ''),
 	'pale': XKCDColor(colorcode: '#fff9d', name: ''),
 	'blue-slash-grey': XKCDColor(colorcode: '#758da', name: ''),
 	'hot-magenta': XKCDColor(colorcode: '#f504c', name: ''),
 	'greyblue': XKCDColor(colorcode: '#77a1b', name: ''),
 	'purpley': XKCDColor(colorcode: '#8756e', name: ''),
 	'baby-shit-green': XKCDColor(colorcode: '#88971', name: ''),
 	'brownish-pink': XKCDColor(colorcode: '#c27e7', name: ''),
 	'dark-aquamarine': XKCDColor(colorcode: '#01737', name: ''),
 	'diarrhea': XKCDColor(colorcode: '#9f830', name: ''),
 	'light-mustard': XKCDColor(colorcode: '#f7d56', name: ''),
 	'pale-sky-blue': XKCDColor(colorcode: '#bdf6f', name: ''),
 	'turtle-green': XKCDColor(colorcode: '#75b84', name: ''),
 	'bright-olive': XKCDColor(colorcode: '#9cbb0', name: ''),
 	'dark-grey-blue': XKCDColor(colorcode: '#29465', name: ''),
 	'greeny-brown': XKCDColor(colorcode: '#69600', name: ''),
 	'lemon-green': XKCDColor(colorcode: '#adf80', name: ''),
 	'light-periwinkle': XKCDColor(colorcode: '#c1c6f', name: ''),
 	'seaweed-green': XKCDColor(colorcode: '#35ad6', name: ''),
 	'sunshine-yellow': XKCDColor(colorcode: '#fffd3', name: ''),
 	'ugly-purple': XKCDColor(colorcode: '#a442a', name: ''),
 	'medium-pink': XKCDColor(colorcode: '#f3619', name: ''),
 	'puke-brown': XKCDColor(colorcode: '#94770', name: ''),
 	'very-light-pink': XKCDColor(colorcode: '#fff4f', name: ''),
 	'viridian': XKCDColor(colorcode: '#1e916', name: ''),
 	'bile': XKCDColor(colorcode: '#b5c30', name: ''),
 	'faded-yellow': XKCDColor(colorcode: '#feff7', name: ''),
 	'very-pale-green': XKCDColor(colorcode: '#cffdb', name: ''),
 	'vibrant-green': XKCDColor(colorcode: '#0add0', name: ''),
 	'bright-lime': XKCDColor(colorcode: '#87fd0', name: ''),
 	'spearmint': XKCDColor(colorcode: '#1ef87', name: ''),
 	'light-aquamarine': XKCDColor(colorcode: '#7bfdc', name: ''),
 	'light-sage': XKCDColor(colorcode: '#bceca', name: ''),
 	'yellowgreen': XKCDColor(colorcode: '#bbf90', name: ''),
 	'baby-poo': XKCDColor(colorcode: '#ab900', name: ''),
 	'dark-seafoam': XKCDColor(colorcode: '#1fb57', name: ''),
 	'deep-teal': XKCDColor(colorcode: '#00555', name: ''),
 	'heather': XKCDColor(colorcode: '#a484a', name: ''),
 	'rust-orange': XKCDColor(colorcode: '#c4550', name: ''),
 	'dirty-blue': XKCDColor(colorcode: '#3f829d;
 	'fern-green': XKCDColor(colorcode: '#548d4', name: ''),
 	'bright-lilac': XKCDColor(colorcode: '#c95ef', name: ''),
 	'weird-green': XKCDColor(colorcode: '#3ae57', name: ''),
 	'peacock-blue': XKCDColor(colorcode: '#01679', name: ''),
 	'avocado-green': XKCDColor(colorcode: '#87a92', name: ''),
 	'faded-orange': XKCDColor(colorcode: '#f0944d;
 	'grape-purple': XKCDColor(colorcode: '#5d145', name: ''),
 	'hot-green': XKCDColor(colorcode: '#25ff2', name: ''),
 	'lime-yellow': XKCDColor(colorcode: '#d0fe1d;
 	'mango': XKCDColor(colorcode: '#ffa62', name: ''),
 	'shamrock': XKCDColor(colorcode: '#01b44', name: ''),
 	'bubblegum': XKCDColor(colorcode: '#ff6cb', name: ''),
 	'purplish-brown': XKCDColor(colorcode: '#6b424', name: ''),
 	'vomit-yellow': XKCDColor(colorcode: '#c7c10', name: ''),
 	'pale-cyan': XKCDColor(colorcode: '#b7fff', name: ''),
 	'key-lime': XKCDColor(colorcode: '#aeff6', name: ''),
 	'tomato-red': XKCDColor(colorcode: '#ec2d0', name: ''),
 	'lightgreen': XKCDColor(colorcode: '#76ff7', name: ''),
 	'merlot': XKCDColor(colorcode: '#73003', name: ''),
 	'night-blue': XKCDColor(colorcode: '#04034', name: ''),
 	'purpleish-pink': XKCDColor(colorcode: '#df4ec', name: ''),
 	'apple': XKCDColor(colorcode: '#6ecb3', name: ''),
 	'baby-poop-green': XKCDColor(colorcode: '#8f980', name: ''),
 	'green-apple': XKCDColor(colorcode: '#5edc1', name: ''),
 	'heliotrope': XKCDColor(colorcode: '#d94ff', name: ''),
 	'yellow-slash-green': XKCDColor(colorcode: '#c8fd3d;
 	'almost-black': XKCDColor(colorcode: '#070d0d;
 	'cool-blue': XKCDColor(colorcode: '#4984b', name: ''),
 	'leafy-green': XKCDColor(colorcode: '#51b73', name: ''),
 	'mustard-brown': XKCDColor(colorcode: '#ac7e0', name: ''),
 	'dusk': XKCDColor(colorcode: '#4e548', name: ''),
 	'dull-brown': XKCDColor(colorcode: '#876e4', name: ''),
 	'frog-green': XKCDColor(colorcode: '#58bc0', name: ''),
 	'vivid-green': XKCDColor(colorcode: '#2fef1', name: ''),
 	'bright-light-green': XKCDColor(colorcode: '#2dfe5', name: ''),
 	'fluro-green': XKCDColor(colorcode: '#0aff0', name: ''),
 	'kiwi': XKCDColor(colorcode: '#9cef4', name: ''),
 	'seaweed': XKCDColor(colorcode: '#18d17', name: ''),
 	'navy-green': XKCDColor(colorcode: '#35530', name: ''),
 	'ultramarine-blue': XKCDColor(colorcode: '#1805d', name: ''),
 	'iris': XKCDColor(colorcode: '#6258c', name: ''),
 	'pastel-orange': XKCDColor(colorcode: '#ff964', name: ''),
 	'yellowish-orange': XKCDColor(colorcode: '#ffab0', name: ''),
 	'perrywinkle': XKCDColor(colorcode: '#8f8ce', name: ''),
 	'tealish': XKCDColor(colorcode: '#24bca', name: ''),
 	'dark-plum': XKCDColor(colorcode: '#3f012', name: ''),
 	'pear': XKCDColor(colorcode: '#cbf85', name: ''),
 	'pinkish-orange': XKCDColor(colorcode: '#ff724', name: ''),
 	'midnight-purple': XKCDColor(colorcode: '#28013', name: ''),
 	'light-urple': XKCDColor(colorcode: '#b36ff', name: ''),
 	'dark-mint': XKCDColor(colorcode: '#48c07', name: ''),
 	'greenish-tan': XKCDColor(colorcode: '#bccb7', name: ''),
 	'light-burgundy': XKCDColor(colorcode: '#a8415', name: ''),
 	'turquoise-blue': XKCDColor(colorcode: '#06b1c', name: ''),
 	'ugly-pink': XKCDColor(colorcode: '#cd758', name: ''),
 	'sandy': XKCDColor(colorcode: '#f1da7', name: ''),
 	'electric-pink': XKCDColor(colorcode: '#ff049', name: ''),
 	'muted-purple': XKCDColor(colorcode: '#805b8', name: ''),
 	'mid-green': XKCDColor(colorcode: '#50a74', name: ''),
 	'greyish': XKCDColor(colorcode: '#a8a49', name: ''),
 	'neon-yellow': XKCDColor(colorcode: '#cfff0', name: ''),
 	'banana': XKCDColor(colorcode: '#ffff7', name: ''),
 	'carnation-pink': XKCDColor(colorcode: '#ff7fa', name: ''),
 	'tomato': XKCDColor(colorcode: '#ef402', name: ''),
 	'sea': XKCDColor(colorcode: '#3c999', name: ''),
 	'muddy-brown': XKCDColor(colorcode: '#88680', name: ''),
 	'turquoise-green': XKCDColor(colorcode: '#04f48', name: ''),
 	'buff': XKCDColor(colorcode: '#fef69', name: ''),
 	'fawn': XKCDColor(colorcode: '#cfaf7', name: ''),
 	'muted-blue': XKCDColor(colorcode: '#3b719', name: ''),
 	'pale-rose': XKCDColor(colorcode: '#fdc1c', name: ''),
 	'dark-mint-green': XKCDColor(colorcode: '#20c07', name: ''),
 	'amethyst': XKCDColor(colorcode: '#9b5fc', name: ''),
 	'blue-slash-green': XKCDColor(colorcode: '#0f9b8', name: ''),
 	'chestnut': XKCDColor(colorcode: '#74280', name: ''),
 	'sick-green': XKCDColor(colorcode: '#9db92', name: ''),
 	'pea': XKCDColor(colorcode: '#a4bf2', name: ''),
 	'rusty-orange': XKCDColor(colorcode: '#cd590', name: ''),
 	'stone': XKCDColor(colorcode: '#ada58', name: ''),
 	'rose-red': XKCDColor(colorcode: '#be013', name: ''),
 	'pale-aqua': XKCDColor(colorcode: '#b8ffe', name: ''),
 	'deep-orange': XKCDColor(colorcode: '#dc4d0', name: ''),
 	'earth': XKCDColor(colorcode: '#a2653', name: ''),
 	'mossy-green': XKCDColor(colorcode: '#638b2', name: ''),
 	'grassy-green': XKCDColor(colorcode: '#419c0', name: ''),
 	'pale-lime-green': XKCDColor(colorcode: '#b1ff6', name: ''),
 	'light-grey-blue': XKCDColor(colorcode: '#9dbcd', name: ''),
 	'pale-grey': XKCDColor(colorcode: '#fdfdf', name: ''),
 	'asparagus': XKCDColor(colorcode: '#77ab5', name: ''),
 	'blueberry': XKCDColor(colorcode: '#46419', name: ''),
 	'purple-red': XKCDColor(colorcode: '#99014', name: ''),
 	'pale-lime': XKCDColor(colorcode: '#befd7', name: ''),
 	'greenish-teal': XKCDColor(colorcode: '#32bf8', name: ''),
 	'caramel': XKCDColor(colorcode: '#af6f0', name: ''),
 	'deep-magenta': XKCDColor(colorcode: '#a0025', name: ''),
 	'light-peach': XKCDColor(colorcode: '#ffd8b', name: ''),
 	'milk-chocolate': XKCDColor(colorcode: '#7f4e1', name: ''),
 	'ocher': XKCDColor(colorcode: '#bf9b0', name: ''),
 	'off-green': XKCDColor(colorcode: '#6ba35', name: ''),
 	'purply-pink': XKCDColor(colorcode: '#f075e', name: ''),
 	'lightblue': XKCDColor(colorcode: '#7bc8f', name: ''),
 	'dusky-blue': XKCDColor(colorcode: '#475f9', name: ''),
 	'golden': XKCDColor(colorcode: '#f5bf0', name: ''),
 	'light-beige': XKCDColor(colorcode: '#fffeb', name: ''),
 	'butter-yellow': XKCDColor(colorcode: '#fffd7', name: ''),
 	'dusky-purple': XKCDColor(colorcode: '#895b7', name: ''),
 	'french-blue': XKCDColor(colorcode: '#436bad;
 	'ugly-yellow': XKCDColor(colorcode: '#d0c10', name: ''),
 	'greeny-yellow': XKCDColor(colorcode: '#c6f80', name: ''),
 	'orangish-red': XKCDColor(colorcode: '#f4360', name: ''),
 	'shamrock-green': XKCDColor(colorcode: '#02c14d;
 	'orangish-brown': XKCDColor(colorcode: '#b25f0', name: ''),
 	'tree-green': XKCDColor(colorcode: '#2a7e1', name: ''),
 	'deep-violet': XKCDColor(colorcode: '#49064', name: ''),
 	'gunmetal': XKCDColor(colorcode: '#53626', name: ''),
 	'blue-slash-purple': XKCDColor(colorcode: '#5a06e', name: ''),
 	'cherry': XKCDColor(colorcode: '#cf023', name: ''),
 	'sandy-brown': XKCDColor(colorcode: '#c4a66', name: ''),
 	'warm-grey': XKCDColor(colorcode: '#978a8', name: ''),
 	'dark-indigo': XKCDColor(colorcode: '#1f095', name: ''),
 	'midnight': XKCDColor(colorcode: '#03012d;
 	'bluey-green': XKCDColor(colorcode: '#2bb17', name: ''),
 	'grey-pink': XKCDColor(colorcode: '#c3909', name: ''),
 	'soft-purple': XKCDColor(colorcode: '#a66fb', name: ''),
 	'blood': XKCDColor(colorcode: '#77000', name: ''),
 	'brown-red': XKCDColor(colorcode: '#922b0', name: ''),
 	'medium-grey': XKCDColor(colorcode: '#7d7f7', name: ''),
 	'berry': XKCDColor(colorcode: '#990f4', name: ''),
 	'poo': XKCDColor(colorcode: '#8f730', name: ''),
 	'purpley-pink': XKCDColor(colorcode: '#c83cb', name: ''),
 	'light-salmon': XKCDColor(colorcode: '#fea99', name: ''),
 	'snot': XKCDColor(colorcode: '#acbb0d;
 	'easter-purple': XKCDColor(colorcode: '#c071f', name: ''),
 	'light-yellow-green': XKCDColor(colorcode: '#ccfd7', name: ''),
 	'dark-navy-blue': XKCDColor(colorcode: '#00022', name: ''),
 	'drab': XKCDColor(colorcode: '#82834', name: ''),
 	'light-rose': XKCDColor(colorcode: '#ffc5c', name: ''),
 	'rouge': XKCDColor(colorcode: '#ab123', name: ''),
 	'purplish-red': XKCDColor(colorcode: '#b0054', name: ''),
 	'slime-green': XKCDColor(colorcode: '#99cc0', name: ''),
 	'baby-poop': XKCDColor(colorcode: '#937c0', name: ''),
 	'irish-green': XKCDColor(colorcode: '#01952', name: ''),
 	'pink-slash-purple': XKCDColor(colorcode: '#ef1de', name: ''),
 	'dark-navy': XKCDColor(colorcode: '#00043', name: ''),
 	'greeny-blue': XKCDColor(colorcode: '#42b39', name: ''),
 	'light-plum': XKCDColor(colorcode: '#9d578', name: ''),
 	'pinkish-grey': XKCDColor(colorcode: '#c8aca', name: ''),
 	'dirty-orange': XKCDColor(colorcode: '#c8760', name: ''),
 	'rust-red': XKCDColor(colorcode: '#aa270', name: ''),
 	'pale-lilac': XKCDColor(colorcode: '#e4cbf', name: ''),
 	'orangey-red': XKCDColor(colorcode: '#fa422', name: ''),
 	'primary-blue': XKCDColor(colorcode: '#0804f', name: ''),
 	'kermit-green': XKCDColor(colorcode: '#5cb20', name: ''),
 	'brownish-purple': XKCDColor(colorcode: '#76424', name: ''),
 	'murky-green': XKCDColor(colorcode: '#6c7a0', name: ''),
 	'wheat': XKCDColor(colorcode: '#fbdd7', name: ''),
 	'very-dark-purple': XKCDColor(colorcode: '#2a013', name: ''),
 	'bottle-green': XKCDColor(colorcode: '#044a0', name: ''),
 	'watermelon': XKCDColor(colorcode: '#fd465', name: ''),
 	'deep-sky-blue': XKCDColor(colorcode: '#0d75f', name: ''),
 	'fire-engine-red': XKCDColor(colorcode: '#fe000', name: ''),
 	'yellow-ochre': XKCDColor(colorcode: '#cb9d0', name: ''),
 	'pumpkin-orange': XKCDColor(colorcode: '#fb7d0', name: ''),
 	'pale-olive': XKCDColor(colorcode: '#b9cc8', name: ''),
 	'light-lilac': XKCDColor(colorcode: '#edc8f', name: ''),
 	'lightish-green': XKCDColor(colorcode: '#61e16', name: ''),
 	'carolina-blue': XKCDColor(colorcode: '#8ab8f', name: ''),
 	'mulberry': XKCDColor(colorcode: '#920a4', name: ''),
 	'shocking-pink': XKCDColor(colorcode: '#fe02a', name: ''),
 	'auburn': XKCDColor(colorcode: '#9a300', name: ''),
 	'bright-lime-green': XKCDColor(colorcode: '#65fe0', name: ''),
 	'celadon': XKCDColor(colorcode: '#befdb', name: ''),
 	'pinkish-brown': XKCDColor(colorcode: '#b1726', name: ''),
 	'poo-brown': XKCDColor(colorcode: '#885f0', name: ''),
 	'bright-sky-blue': XKCDColor(colorcode: '#02ccf', name: ''),
 	'celery': XKCDColor(colorcode: '#c1fd9', name: ''),
 	'dirt-brown': XKCDColor(colorcode: '#83653', name: ''),
 	'strawberry': XKCDColor(colorcode: '#fb294', name: ''),
 	'dark-lime': XKCDColor(colorcode: '#84b70', name: ''),
 	'copper': XKCDColor(colorcode: '#b6632', name: ''),
 	'medium-brown': XKCDColor(colorcode: '#7f511', name: ''),
 	'muted-green': XKCDColor(colorcode: '#5fa05', name: ''),
 	'robins-egg': XKCDColor(colorcode: '#6dedfd;
 	'bright-aqua': XKCDColor(colorcode: '#0bf9e', name: ''),
 	'bright-lavender': XKCDColor(colorcode: '#c760f', name: ''),
 	'ivory': XKCDColor(colorcode: '#ffffc', name: ''),
 	'very-light-purple': XKCDColor(colorcode: '#f6cef', name: ''),
 	'light-navy': XKCDColor(colorcode: '#15508', name: ''),
 	'pink-red': XKCDColor(colorcode: '#f5054', name: ''),
 	'olive-brown': XKCDColor(colorcode: '#64540', name: ''),
 	'poop-brown': XKCDColor(colorcode: '#7a590', name: ''),
 	'mustard-green': XKCDColor(colorcode: '#a8b50', name: ''),
 	'ocean-green': XKCDColor(colorcode: '#3d997', name: ''),
 	'very-dark-blue': XKCDColor(colorcode: '#00013', name: ''),
 	'dusty-green': XKCDColor(colorcode: '#76a97', name: ''),
 	'light-navy-blue': XKCDColor(colorcode: '#2e5a8', name: ''),
 	'minty-green': XKCDColor(colorcode: '#0bf77d;
 	'adobe': XKCDColor(colorcode: '#bd6c4', name: ''),
 	'barney': XKCDColor(colorcode: '#ac1db', name: ''),
 	'jade-green': XKCDColor(colorcode: '#2baf6', name: ''),
 	'bright-light-blue': XKCDColor(colorcode: '#26f7fd;
 	'light-lime': XKCDColor(colorcode: '#aefd6', name: ''),
 	'dark-khaki': XKCDColor(colorcode: '#9b8f5', name: ''),
 	'orange-yellow': XKCDColor(colorcode: '#ffad0', name: ''),
 	'ocre': XKCDColor(colorcode: '#c69c0', name: ''),
 	'maize': XKCDColor(colorcode: '#f4d05', name: ''),
 	'faded-pink': XKCDColor(colorcode: '#de9da', name: ''),
 	'british-racing-green': XKCDColor(colorcode: '#05480d;
 	'sandstone': XKCDColor(colorcode: '#c9ae7', name: ''),
 	'mud-brown': XKCDColor(colorcode: '#60460', name: ''),
 	'light-sea-green': XKCDColor(colorcode: '#98f6b', name: ''),
 	'robin-egg-blue': XKCDColor(colorcode: '#8af1f', name: ''),
 	'aqua-marine': XKCDColor(colorcode: '#2ee8b', name: ''),
 	'dark-sea-green': XKCDColor(colorcode: '#11875d;
 	'soft-pink': XKCDColor(colorcode: '#fdb0c', name: ''),
 	'orangey-brown': XKCDColor(colorcode: '#b1600', name: ''),
 	'cherry-red': XKCDColor(colorcode: '#f7022', name: ''),
 	'burnt-yellow': XKCDColor(colorcode: '#d5ab0', name: ''),
 	'brownish-grey': XKCDColor(colorcode: '#86775', name: ''),
 	'camel': XKCDColor(colorcode: '#c69f5', name: ''),
 	'purplish-grey': XKCDColor(colorcode: '#7a687', name: ''),
 	'marine': XKCDColor(colorcode: '#042e6', name: ''),
 	'greyish-pink': XKCDColor(colorcode: '#c88d9', name: ''),
 	'pale-turquoise': XKCDColor(colorcode: '#a5fbd', name: ''),
 	'pastel-yellow': XKCDColor(colorcode: '#fffe7', name: ''),
 	'bluey-purple': XKCDColor(colorcode: '#6241c', name: ''),
 	'canary-yellow': XKCDColor(colorcode: '#fffe4', name: ''),
 	'faded-red': XKCDColor(colorcode: '#d3494', name: ''),
 	'sepia': XKCDColor(colorcode: '#985e2', name: ''),
 	'coffee': XKCDColor(colorcode: '#a6814', name: ''),
 	'bright-magenta': XKCDColor(colorcode: '#ff08e', name: ''),
 	'mocha': XKCDColor(colorcode: '#9d765', name: ''),
 	'ecru': XKCDColor(colorcode: '#feffc', name: ''),
 	'purpleish': XKCDColor(colorcode: '#98568d;
 	'cranberry': XKCDColor(colorcode: '#9e003', name: ''),
 	'darkish-green': XKCDColor(colorcode: '#287c3', name: ''),
 	'brown-orange': XKCDColor(colorcode: '#b9690', name: ''),
 	'dusky-rose': XKCDColor(colorcode: '#ba687', name: ''),
 	'melon': XKCDColor(colorcode: '#ff785', name: ''),
 	'sickly-green': XKCDColor(colorcode: '#94b21', name: ''),
 	'silver': XKCDColor(colorcode: '#c5c9c', name: ''),
 	'purply-blue': XKCDColor(colorcode: '#661ae', name: ''),
 	'purpleish-blue': XKCDColor(colorcode: '#6140e', name: ''),
 	'hospital-green': XKCDColor(colorcode: '#9be5a', name: ''),
 	'shit-brown': XKCDColor(colorcode: '#7b580', name: ''),
 	'mid-blue': XKCDColor(colorcode: '#276ab', name: ''),
 	'amber': XKCDColor(colorcode: '#feb30', name: ''),
 	'easter-green': XKCDColor(colorcode: '#8cfd7', name: ''),
 	'soft-blue': XKCDColor(colorcode: '#6488e', name: ''),
 	'cerulean-blue': XKCDColor(colorcode: '#056ee', name: ''),
 	'golden-brown': XKCDColor(colorcode: '#b27a0', name: ''),
 	'bright-turquoise': XKCDColor(colorcode: '#0ffef', name: ''),
 	'red-pink': XKCDColor(colorcode: '#fa2a5', name: ''),
 	'red-purple': XKCDColor(colorcode: '#82074', name: ''),
 	'greyish-brown': XKCDColor(colorcode: '#7a6a4', name: ''),
 	'vermillion': XKCDColor(colorcode: '#f4320', name: ''),
 	'russet': XKCDColor(colorcode: '#a1390', name: ''),
 	'steel-grey': XKCDColor(colorcode: '#6f828', name: ''),
 	'lighter-purple': XKCDColor(colorcode: '#a55af', name: ''),
 	'bright-violet': XKCDColor(colorcode: '#ad0afd;
 	'prussian-blue': XKCDColor(colorcode: '#00457', name: ''),
 	'slate-green': XKCDColor(colorcode: '#658d6d;
 	'dirty-pink': XKCDColor(colorcode: '#ca7b8', name: ''),
 	'dark-blue-green': XKCDColor(colorcode: '#00524', name: ''),
 	'pine': XKCDColor(colorcode: '#2b5d3', name: ''),
 	'yellowy-green': XKCDColor(colorcode: '#bff12', name: ''),
 	'dark-gold': XKCDColor(colorcode: '#b5941', name: ''),
 	'bluish': XKCDColor(colorcode: '#2976b', name: ''),
 	'darkish-blue': XKCDColor(colorcode: '#01418', name: ''),
 	'dull-red': XKCDColor(colorcode: '#bb3f3', name: ''),
 	'pinky-red': XKCDColor(colorcode: '#fc264', name: ''),
 	'bronze': XKCDColor(colorcode: '#a8790', name: ''),
 	'pale-teal': XKCDColor(colorcode: '#82cbb', name: ''),
 	'military-green': XKCDColor(colorcode: '#667c3', name: ''),
 	'barbie-pink': XKCDColor(colorcode: '#fe46a', name: ''),
 	'bubblegum-pink': XKCDColor(colorcode: '#fe83c', name: ''),
 	'pea-soup-green': XKCDColor(colorcode: '#94a61', name: ''),
 	'dark-mustard': XKCDColor(colorcode: '#a8890', name: ''),
 	'shit': XKCDColor(colorcode: '#7f5f0', name: ''),
 	'medium-purple': XKCDColor(colorcode: '#9e43a', name: ''),
 	'very-dark-green': XKCDColor(colorcode: '#062e0', name: ''),
 	'dirt': XKCDColor(colorcode: '#8a6e4', name: ''),
 	'dusky-pink': XKCDColor(colorcode: '#cc7a8', name: ''),
 	'red-violet': XKCDColor(colorcode: '#9e016', name: ''),
 	'lemon-yellow': XKCDColor(colorcode: '#fdff3', name: ''),
 	'pistachio': XKCDColor(colorcode: '#c0fa8', name: ''),
 	'dull-yellow': XKCDColor(colorcode: '#eedc5', name: ''),
 	'dark-lime-green': XKCDColor(colorcode: '#7ebd0', name: ''),
 	'denim-blue': XKCDColor(colorcode: '#3b5b9', name: ''),
 	'teal-blue': XKCDColor(colorcode: '#01889', name: ''),
 	'lightish-blue': XKCDColor(colorcode: '#3d7afd;
 	'purpley-blue': XKCDColor(colorcode: '#5f34e', name: ''),
 	'light-indigo': XKCDColor(colorcode: '#6d5ac', name: ''),
 	'swamp-green': XKCDColor(colorcode: '#74850', name: ''),
 	'brown-green': XKCDColor(colorcode: '#706c1', name: ''),
 	'dark-maroon': XKCDColor(colorcode: '#3c000', name: ''),
 	'hot-purple': XKCDColor(colorcode: '#cb00f', name: ''),
 	'dark-forest-green': XKCDColor(colorcode: '#002d0', name: ''),
 	'faded-blue': XKCDColor(colorcode: '#658cb', name: ''),
 	'drab-green': XKCDColor(colorcode: '#74955', name: ''),
 	'light-lime-green': XKCDColor(colorcode: '#b9ff6', name: ''),
 	'snot-green': XKCDColor(colorcode: '#9dc10', name: ''),
 	'yellowish': XKCDColor(colorcode: '#faee6', name: ''),
 	'light-blue-green': XKCDColor(colorcode: '#7efbb', name: ''),
 	'bordeaux': XKCDColor(colorcode: '#7b002', name: ''),
 	'light-mauve': XKCDColor(colorcode: '#c292a', name: ''),
 	'ocean': XKCDColor(colorcode: '#017b9', name: ''),
 	'marigold': XKCDColor(colorcode: '#fcc00', name: ''),
 	'muddy-green': XKCDColor(colorcode: '#65743', name: ''),
 	'dull-orange': XKCDColor(colorcode: '#d8863', name: ''),
 	'steel': XKCDColor(colorcode: '#73859', name: ''),
 	'electric-purple': XKCDColor(colorcode: '#aa23f', name: ''),
 	'fluorescent-green': XKCDColor(colorcode: '#08ff0', name: ''),
 	'yellowish-brown': XKCDColor(colorcode: '#9b7a0', name: ''),
 	'blush': XKCDColor(colorcode: '#f29e8', name: ''),
 	'soft-green': XKCDColor(colorcode: '#6fc27', name: ''),
 	'bright-orange': XKCDColor(colorcode: '#ff5b0', name: ''),
 	'lemon': XKCDColor(colorcode: '#fdff5', name: ''),
 	'purple-grey': XKCDColor(colorcode: '#866f8', name: ''),
 	'acid-green': XKCDColor(colorcode: '#8ffe0', name: ''),
 	'pale-lavender': XKCDColor(colorcode: '#eecff', name: ''),
 	'violet-blue': XKCDColor(colorcode: '#510ac', name: ''),
 	'light-forest-green': XKCDColor(colorcode: '#4f915', name: ''),
 	'burnt-red': XKCDColor(colorcode: '#9f230', name: ''),
 	'khaki-green': XKCDColor(colorcode: '#72863', name: ''),
 	'cerise': XKCDColor(colorcode: '#de0c6', name: ''),
 	'faded-purple': XKCDColor(colorcode: '#916e9', name: ''),
 	'apricot': XKCDColor(colorcode: '#ffb16d;
 	'dark-olive-green': XKCDColor(colorcode: '#3c4d0', name: ''),
 	'grey-brown': XKCDColor(colorcode: '#7f705', name: ''),
 	'green-grey': XKCDColor(colorcode: '#77926', name: ''),
 	'true-blue': XKCDColor(colorcode: '#010fc', name: ''),
 	'pale-violet': XKCDColor(colorcode: '#ceaef', name: ''),
 	'periwinkle-blue': XKCDColor(colorcode: '#8f99f', name: ''),
 	'light-sky-blue': XKCDColor(colorcode: '#c6fcf', name: ''),
 	'blurple': XKCDColor(colorcode: '#5539c', name: ''),
 	'green-brown': XKCDColor(colorcode: '#544e0', name: ''),
 	'bluegreen': XKCDColor(colorcode: '#017a7', name: ''),
 	'bright-teal': XKCDColor(colorcode: '#01f9c', name: ''),
 	'brownish-yellow': XKCDColor(colorcode: '#c9b00', name: ''),
 	'pea-soup': XKCDColor(colorcode: '#92990', name: ''),
 	'forest': XKCDColor(colorcode: '#0b550', name: ''),
 	'barney-purple': XKCDColor(colorcode: '#a0049', name: ''),
 	'ultramarine': XKCDColor(colorcode: '#2000b', name: ''),
 	'purplish': XKCDColor(colorcode: '#94568', name: ''),
 	'puke-yellow': XKCDColor(colorcode: '#c2be0', name: ''),
 	'bluish-grey': XKCDColor(colorcode: '#748b9', name: ''),
 	'dark-periwinkle': XKCDColor(colorcode: '#665fd', name: ''),
 	'dark-lilac': XKCDColor(colorcode: '#9c6da', name: ''),
 	'reddish': XKCDColor(colorcode: '#c4424', name: ''),
 	'light-maroon': XKCDColor(colorcode: '#a2485', name: ''),
 	'dusty-purple': XKCDColor(colorcode: '#825f8', name: ''),
 	'terra-cotta': XKCDColor(colorcode: '#c9643', name: ''),
 	'avocado': XKCDColor(colorcode: '#90b13', name: ''),
 	'marine-blue': XKCDColor(colorcode: '#01386', name: ''),
 	'teal-green': XKCDColor(colorcode: '#25a36', name: ''),
 	'slate-grey': XKCDColor(colorcode: '#59656d;
 	'lighter-green': XKCDColor(colorcode: '#75fd6', name: ''),
 	'electric-green': XKCDColor(colorcode: '#21fc0d;
 	'dusty-blue': XKCDColor(colorcode: '#5a86ad;
 	'golden-yellow': XKCDColor(colorcode: '#fec61', name: ''),
 	'bright-yellow': XKCDColor(colorcode: '#fffd0', name: ''),
 	'light-lavender': XKCDColor(colorcode: '#dfc5f', name: ''),
 	'umber': XKCDColor(colorcode: '#b2640', name: ''),
 	'poop': XKCDColor(colorcode: '#7f5e0', name: ''),
 	'dark-peach': XKCDColor(colorcode: '#de7e5d;
 	'jungle-green': XKCDColor(colorcode: '#04824', name: ''),
 	'eggshell': XKCDColor(colorcode: '#ffffd', name: ''),
 	'denim': XKCDColor(colorcode: '#3b638', name: ''),
 	'yellow-brown': XKCDColor(colorcode: '#b7940', name: ''),
 	'dull-purple': XKCDColor(colorcode: '#84597', name: ''),
 	'chocolate-brown': XKCDColor(colorcode: '#41190', name: ''),
 	'wine-red': XKCDColor(colorcode: '#7b032', name: ''),
 	'neon-blue': XKCDColor(colorcode: '#04d9f', name: ''),
 	'dirty-green': XKCDColor(colorcode: '#667e2', name: ''),
 	'light-tan': XKCDColor(colorcode: '#fbeea', name: ''),
 	'ice-blue': XKCDColor(colorcode: '#d7fff', name: ''),
 	'cadet-blue': XKCDColor(colorcode: '#4e749', name: ''),
 	'dark-mauve': XKCDColor(colorcode: '#874c6', name: ''),
 	'very-light-blue': XKCDColor(colorcode: '#d5fff', name: ''),
 	'grey-purple': XKCDColor(colorcode: '#826d8', name: ''),
 	'pastel-pink': XKCDColor(colorcode: '#ffbacd;
 	'very-light-green': XKCDColor(colorcode: '#d1ffbd;
 	'dark-sky-blue': XKCDColor(colorcode: '#448ee', name: ''),
 	'evergreen': XKCDColor(colorcode: '#05472', name: ''),
 	'dull-pink': XKCDColor(colorcode: '#d5869d;
 	'aubergine': XKCDColor(colorcode: '#3d073', name: ''),
 	'mahogany': XKCDColor(colorcode: '#4a010', name: ''),
 	'reddish-orange': XKCDColor(colorcode: '#f8481', name: ''),
 	'deep-green': XKCDColor(colorcode: '#02590', name: ''),
 	'vomit-green': XKCDColor(colorcode: '#89a20', name: ''),
 	'purple-pink': XKCDColor(colorcode: '#e03fd', name: ''),
 	'dusty-pink': XKCDColor(colorcode: '#d58a9', name: ''),
 	'faded-green': XKCDColor(colorcode: '#7bb27', name: ''),
 	'camo-green': XKCDColor(colorcode: '#52652', name: ''),
 	'pinky-purple': XKCDColor(colorcode: '#c94cb', name: ''),
 	'pink-purple': XKCDColor(colorcode: '#db4bd', name: ''),
 	'brownish-red': XKCDColor(colorcode: '#9e362', name: ''),
 	'dark-rose': XKCDColor(colorcode: '#b5485d;
 	'mud': XKCDColor(colorcode: '#735c1', name: ''),
 	'brownish': XKCDColor(colorcode: '#9c6d5', name: ''),
 	'emerald-green': XKCDColor(colorcode: '#028f1', name: ''),
 	'pale-brown': XKCDColor(colorcode: '#b1916', name: ''),
 	'dull-blue': XKCDColor(colorcode: '#49759', name: ''),
 	'burnt-umber': XKCDColor(colorcode: '#a0450', name: ''),
 	'medium-green': XKCDColor(colorcode: '#39ad4', name: ''),
 	'clay': XKCDColor(colorcode: '#b66a5', name: ''),
 	'light-aqua': XKCDColor(colorcode: '#8cffd', name: ''),
 	'light-olive-green': XKCDColor(colorcode: '#a4be5', name: ''),
 	'brownish-orange': XKCDColor(colorcode: '#cb772', name: ''),
 	'dark-aqua': XKCDColor(colorcode: '#05696', name: ''),
 	'purplish-pink': XKCDColor(colorcode: '#ce5da', name: ''),
 	'dark-salmon': XKCDColor(colorcode: '#c85a5', name: ''),
 	'greenish-grey': XKCDColor(colorcode: '#96ae8d;
 	'jade': XKCDColor(colorcode: '#1fa77', name: ''),
 	'ugly-green': XKCDColor(colorcode: '#7a970', name: ''),
 	'dark-beige': XKCDColor(colorcode: '#ac936', name: ''),
 	'emerald': XKCDColor(colorcode: '#01a04', name: ''),
 	'pale-red': XKCDColor(colorcode: '#d9544d;
 	'light-magenta': XKCDColor(colorcode: '#fa5ff', name: ''),
 	'sky': XKCDColor(colorcode: '#82caf', name: ''),
 	'light-cyan': XKCDColor(colorcode: '#acfff', name: ''),
 	'yellow-orange': XKCDColor(colorcode: '#fcb00', name: ''),
 	'reddish-purple': XKCDColor(colorcode: '#91095', name: ''),
 	'reddish-pink': XKCDColor(colorcode: '#fe2c5', name: ''),
 	'orchid': XKCDColor(colorcode: '#c875c', name: ''),
 	'dirty-yellow': XKCDColor(colorcode: '#cdc50', name: ''),
 	'orange-red': XKCDColor(colorcode: '#fd411', name: ''),
 	'deep-red': XKCDColor(colorcode: '#9a020', name: ''),
 	'orange-brown': XKCDColor(colorcode: '#be640', name: ''),
 	'cobalt-blue': XKCDColor(colorcode: '#030aa', name: ''),
 	'neon-pink': XKCDColor(colorcode: '#fe019', name: ''),
 	'rose-pink': XKCDColor(colorcode: '#f7879', name: ''),
 	'greyish-purple': XKCDColor(colorcode: '#88719', name: ''),
 	'raspberry': XKCDColor(colorcode: '#b0014', name: ''),
 	'aqua-green': XKCDColor(colorcode: '#12e19', name: ''),
 	'salmon-pink': XKCDColor(colorcode: '#fe7b7', name: ''),
 	'tangerine': XKCDColor(colorcode: '#ff940', name: ''),
 	'brownish-green': XKCDColor(colorcode: '#6a6e0', name: ''),
 	'red-brown': XKCDColor(colorcode: '#8b2e1', name: ''),
 	'greenish-brown': XKCDColor(colorcode: '#69611', name: ''),
 	'pumpkin': XKCDColor(colorcode: '#e1770', name: ''),
 	'pine-green': XKCDColor(colorcode: '#0a481', name: ''),
 	'charcoal': XKCDColor(colorcode: '#34383', name: ''),
 	'baby-pink': XKCDColor(colorcode: '#ffb7c', name: ''),
 	'cornflower': XKCDColor(colorcode: '#6a79f', name: ''),
 	'blue-violet': XKCDColor(colorcode: '#5d06e', name: ''),
 	'chocolate': XKCDColor(colorcode: '#3d1c0', name: ''),
 	'greyish-green': XKCDColor(colorcode: '#82a67d;
 	'scarlet': XKCDColor(colorcode: '#be011', name: ''),
 	'green-yellow': XKCDColor(colorcode: '#c9ff2', name: ''),
 	'dark-olive': XKCDColor(colorcode: '#373e0', name: ''),
 	'sienna': XKCDColor(colorcode: '#a9561', name: ''),
 	'pastel-purple': XKCDColor(colorcode: '#caa0f', name: ''),
 	'terracotta': XKCDColor(colorcode: '#ca664', name: ''),
 	'aqua-blue': XKCDColor(colorcode: '#02d8e', name: ''),
 	'sage-green': XKCDColor(colorcode: '#88b37', name: ''),
 	'blood-red': XKCDColor(colorcode: '#98000', name: ''),
 	'deep-pink': XKCDColor(colorcode: '#cb016', name: ''),
 	'grass': XKCDColor(colorcode: '#5cac2d;
 	'moss': XKCDColor(colorcode: '#76995', name: ''),
 	'pastel-blue': XKCDColor(colorcode: '#a2bff', name: ''),
 	'bluish-green': XKCDColor(colorcode: '#10a67', name: ''),
 	'green-blue': XKCDColor(colorcode: '#06b48', name: ''),
 	'dark-tan': XKCDColor(colorcode: '#af884', name: ''),
 	'greenish-blue': XKCDColor(colorcode: '#0b8b8', name: ''),
 	'pale-orange': XKCDColor(colorcode: '#ffa75', name: ''),
 	'vomit': XKCDColor(colorcode: '#a2a41', name: ''),
 	'forrest-green': XKCDColor(colorcode: '#15440', name: ''),
 	'dark-lavender': XKCDColor(colorcode: '#85679', name: ''),
 	'dark-violet': XKCDColor(colorcode: '#34013', name: ''),
 	'purple-blue': XKCDColor(colorcode: '#632de', name: ''),
 	'dark-cyan': XKCDColor(colorcode: '#0a888', name: ''),
 	'olive-drab': XKCDColor(colorcode: '#6f763', name: ''),
 	'pinkish': XKCDColor(colorcode: '#d46a7', name: ''),
 	'cobalt': XKCDColor(colorcode: '#1e488', name: ''),
 	'neon-purple': XKCDColor(colorcode: '#bc13f', name: ''),
 	'light-turquoise': XKCDColor(colorcode: '#7ef4c', name: ''),
 	'apple-green': XKCDColor(colorcode: '#76cd2', name: ''),
 	'dull-green': XKCDColor(colorcode: '#74a66', name: ''),
 	'wine': XKCDColor(colorcode: '#80013', name: ''),
 	'powder-blue': XKCDColor(colorcode: '#b1d1f', name: ''),
 	'off-white': XKCDColor(colorcode: '#ffffe', name: ''),
 	'electric-blue': XKCDColor(colorcode: '#0652f', name: ''),
 	'dark-turquoise': XKCDColor(colorcode: '#045c5', name: ''),
 	'blue-purple': XKCDColor(colorcode: '#5729c', name: ''),
 	'azure': XKCDColor(colorcode: '#069af', name: ''),
 	'bright-red': XKCDColor(colorcode: '#ff000d;
 	'pinkish-red': XKCDColor(colorcode: '#f10c4', name: ''),
 	'cornflower-blue': XKCDColor(colorcode: '#5170d', name: ''),
 	'light-olive': XKCDColor(colorcode: '#acbf6', name: ''),
 	'grape': XKCDColor(colorcode: '#6c346', name: ''),
 	'greyish-blue': XKCDColor(colorcode: '#5e819d;
 	'purplish-blue': XKCDColor(colorcode: '#601ef', name: ''),
 	'yellowish-green': XKCDColor(colorcode: '#b0dd1', name: ''),
 	'greenish-yellow': XKCDColor(colorcode: '#cdfd0', name: ''),
 	'medium-blue': XKCDColor(colorcode: '#2c6fb', name: ''),
 	'dusty-rose': XKCDColor(colorcode: '#c0737', name: ''),
 	'light-violet': XKCDColor(colorcode: '#d6b4f', name: ''),
 	'midnight-blue': XKCDColor(colorcode: '#02003', name: ''),
 	'bluish-purple': XKCDColor(colorcode: '#703be', name: ''),
 	'red-orange': XKCDColor(colorcode: '#fd3c0', name: ''),
 	'dark-magenta': XKCDColor(colorcode: '#96005', name: ''),
 	'greenish': XKCDColor(colorcode: '#40a36', name: ''),
 	'ocean-blue': XKCDColor(colorcode: '#03719', name: ''),
 	'coral': XKCDColor(colorcode: '#fc5a5', name: ''),
 	'cream': XKCDColor(colorcode: '#ffffc', name: ''),
 	'reddish-brown': XKCDColor(colorcode: '#7f2b0', name: ''),
 	'burnt-sienna': XKCDColor(colorcode: '#b04e0', name: ''),
 	'brick': XKCDColor(colorcode: '#a0362', name: ''),
 	'sage': XKCDColor(colorcode: '#87ae7', name: ''),
 	'grey-green': XKCDColor(colorcode: '#789b7', name: ''),
 	'white': XKCDColor(colorcode: '#fffff', name: ''),
 	'robins-egg-blue': XKCDColor(colorcode: '#98eff', name: ''),
 	'moss-green': XKCDColor(colorcode: '#658b3', name: ''),
 	'steel-blue': XKCDColor(colorcode: '#5a7d9', name: ''),
 	'eggplant': XKCDColor(colorcode: '#38083', name: ''),
 	'light-yellow': XKCDColor(colorcode: '#fffe7', name: ''),
 	'leaf-green': XKCDColor(colorcode: '#5ca90', name: ''),
 	'light-grey': XKCDColor(colorcode: '#d8dcd', name: ''),
 	'puke': XKCDColor(colorcode: '#a5a50', name: ''),
 	'pinkish-purple': XKCDColor(colorcode: '#d648d', name: ''),
 	'sea-blue': XKCDColor(colorcode: '#04749', name: ''),
 	'pale-purple': XKCDColor(colorcode: '#b790d', name: ''),
 	'slate-blue': XKCDColor(colorcode: '#5b7c9', name: ''),
 	'blue-grey': XKCDColor(colorcode: '#607c8', name: ''),
 	'hunter-green': XKCDColor(colorcode: '#0b400', name: ''),
 	'fuchsia': XKCDColor(colorcode: '#ed0dd', name: ''),
 	'crimson': XKCDColor(colorcode: '#8c000', name: ''),
 	'pale-yellow': XKCDColor(colorcode: '#ffff8', name: ''),
 	'ochre': XKCDColor(colorcode: '#bf900', name: ''),
 	'mustard-yellow': XKCDColor(colorcode: '#d2bd0', name: ''),
 	'light-red': XKCDColor(colorcode: '#ff474', name: ''),
 	'cerulean': XKCDColor(colorcode: '#0485d', name: ''),
 	'pale-pink': XKCDColor(colorcode: '#ffcfd', name: ''),
 	'deep-blue': XKCDColor(colorcode: '#04027', name: ''),
 	'rust': XKCDColor(colorcode: '#a83c0', name: ''),
 	'light-teal': XKCDColor(colorcode: '#90e4c', name: ''),
 	'slate': XKCDColor(colorcode: '#51657', name: ''),
 	'goldenrod': XKCDColor(colorcode: '#fac20', name: ''),
 	'dark-yellow': XKCDColor(colorcode: '#d5b60', name: ''),
 	'dark-grey': XKCDColor(colorcode: '#36373', name: ''),
 	'army-green': XKCDColor(colorcode: '#4b5d1', name: ''),
 	'grey-blue': XKCDColor(colorcode: '#6b8ba', name: ''),
 	'seafoam': XKCDColor(colorcode: '#80f9ad;
 	'puce': XKCDColor(colorcode: '#a57e5', name: ''),
 	'spring-green': XKCDColor(colorcode: '#a9f97', name: ''),
 	'dark-orange': XKCDColor(colorcode: '#c6510', name: ''),
 	'sand': XKCDColor(colorcode: '#e2ca7', name: ''),
 	'pastel-green': XKCDColor(colorcode: '#b0ff9d;
 	'mint': XKCDColor(colorcode: '#9ffeb', name: ''),
 	'light-orange': XKCDColor(colorcode: '#fdaa4', name: ''),
 	'bright-pink': XKCDColor(colorcode: '#fe01b', name: ''),
 	'chartreuse': XKCDColor(colorcode: '#c1f80', name: ''),
 	'deep-purple': XKCDColor(colorcode: '#36013', name: ''),
 	'dark-brown': XKCDColor(colorcode: '#341c0', name: ''),
 	'taupe': XKCDColor(colorcode: '#b9a28', name: ''),
 	'pea-green': XKCDColor(colorcode: '#8eab1', name: ''),
 	'puke-green': XKCDColor(colorcode: '#9aae0', name: ''),
 	'kelly-green': XKCDColor(colorcode: '#02ab2', name: ''),
 	'seafoam-green': XKCDColor(colorcode: '#7af9a', name: ''),
 	'blue-green': XKCDColor(colorcode: '#137e6d;
 	'khaki': XKCDColor(colorcode: '#aaa66', name: ''),
 	'burgundy': XKCDColor(colorcode: '#61002', name: ''),
 	'dark-teal': XKCDColor(colorcode: '#014d4', name: ''),
 	'brick-red': XKCDColor(colorcode: '#8f140', name: ''),
 	'royal-purple': XKCDColor(colorcode: '#4b006', name: ''),
 	'plum': XKCDColor(colorcode: '#580f4', name: ''),
 	'mint-green': XKCDColor(colorcode: '#8fff9', name: ''),
 	'gold': XKCDColor(colorcode: '#dbb40', name: ''),
 	'baby-blue': XKCDColor(colorcode: '#a2cff', name: ''),
 	'yellow-green': XKCDColor(colorcode: '#c0fb2d;
 	'bright-purple': XKCDColor(colorcode: '#be03fd;
 	'dark-red': XKCDColor(colorcode: '#84000', name: ''),
 	'pale-blue': XKCDColor(colorcode: '#d0fef', name: ''),
 	'grass-green': XKCDColor(colorcode: '#3f9b0', name: ''),
 	'navy': XKCDColor(colorcode: '#01153', name: ''),
 	'aquamarine': XKCDColor(colorcode: '#04d8b', name: ''),
 	'burnt-orange': XKCDColor(colorcode: '#c04e0', name: ''),
 	'neon-green': XKCDColor(colorcode: '#0cff0', name: ''),
 	'bright-blue': XKCDColor(colorcode: '#0165f', name: ''),
 	'rose': XKCDColor(colorcode: '#cf627', name: ''),
 	'light-pink': XKCDColor(colorcode: '#ffd1d', name: ''),
 	'mustard': XKCDColor(colorcode: '#ceb30', name: ''),
 	'indigo': XKCDColor(colorcode: '#38028', name: ''),
 	'lime': XKCDColor(colorcode: '#aaff3', name: ''),
 	'sea-green': XKCDColor(colorcode: '#53fca', name: ''),
 	'periwinkle': XKCDColor(colorcode: '#8e82f', name: ''),
 	'dark-pink': XKCDColor(colorcode: '#cb416', name: ''),
 	'olive-green': XKCDColor(colorcode: '#677a0', name: ''),
 	'peach': XKCDColor(colorcode: '#ffb07', name: ''),
 	'pale-green': XKCDColor(colorcode: '#c7fdb', name: ''),
 	'light-brown': XKCDColor(colorcode: '#ad815', name: ''),
 	'hot-pink': XKCDColor(colorcode: '#ff028d;
 	'black': XKCDColor(colorcode: '#00000', name: ''),
 	'lilac': XKCDColor(colorcode: '#cea2fd;
 	'navy-blue': XKCDColor(colorcode: '#00114', name: ''),
 	'royal-blue': XKCDColor(colorcode: '#0504a', name: ''),
 	'beige': XKCDColor(colorcode: '#e6daa', name: ''),
 	'salmon': XKCDColor(colorcode: '#ff796', name: ''),
 	'olive': XKCDColor(colorcode: '#6e750', name: ''),
 	'maroon': XKCDColor(colorcode: '#65002', name: ''),
 	'bright-green': XKCDColor(colorcode: '#01ff0', name: ''),
 	'dark-purple': XKCDColor(colorcode: '#35063', name: ''),
 	'mauve': XKCDColor(colorcode: '#ae718', name: ''),
 	'forest-green': XKCDColor(colorcode: '#06470', name: ''),
 	'aqua': XKCDColor(colorcode: '#13eac', name: ''),
 	'cyan': XKCDColor(colorcode: '#00fff', name: ''),
 	'tan': XKCDColor(colorcode: '#d1b26', name: ''),
 	'dark-blue': XKCDColor(colorcode: '#00035', name: ''),
 	'lavender': XKCDColor(colorcode: '#c79fe', name: ''),
 	'turquoise': XKCDColor(colorcode: '#06c2a', name: ''),
 	'dark-green': XKCDColor(colorcode: '#03350', name: ''),
 	'violet': XKCDColor(colorcode: '#9a0ee', name: ''),
 	'light-purple': XKCDColor(colorcode: '#bf77f', name: ''),
 	'lime-green': XKCDColor(colorcode: '#89fe0', name: ''),
 	'grey': XKCDColor(colorcode: '#92959', name: ''),
 	'sky-blue': XKCDColor(colorcode: '#75bbfd;
 	'yellow': XKCDColor(colorcode: '#ffff1', name: ''),
 	'magenta': XKCDColor(colorcode: '#c2007', name: ''),
 	'light-green': XKCDColor(colorcode: '#96f97', name: ''),
 	'orange': XKCDColor(colorcode: '#f9730', name: ''),
 	'teal': XKCDColor(colorcode: '#02938', name: ''),
 	'light-blue': XKCDColor(colorcode: '#95d0f', name: ''),
 	'red': XKCDColor(colorcode: '#e5000', name: ''),
 	'brown': XKCDColor(colorcode: '#65370', name: ''),
 	'pink': XKCDColor(colorcode: '#ff81c', name: ''),
 	'blue': XKCDColor(colorcode: '#0343d', name: ''),
 	'green': XKCDColor(colorcode: '#15b01', name: ''),
 	'purple': XKCDColor(colorcode: '#7e1e9', name: ''),
};

MapEntry<String, XKCDColor>? _xkcdByRGB(RGB rgb) {
  var hexCode = HexCode.fromRGB(rgb);
  return XKCD_COLOR_CODES.entries
      .firstWhereOrNull((element) => element.value.colorcode.toLowerCase() == hexCode.toString().toLowerCase());
}

Map<String, XKCDColor> findSimilarRALColors(RGB rgb) {
  var xkcd = _xkcdByRGB(rgb);
  if (xkcd != null) return <String, XKCDColor>{xkcd.key: xkcd.value};

  var XKCDRGBs = XKCD_COLOR_CODES.values.map((xkcd) => HexCode(xkcd.colorcode).toRGB()).toList();

  var out = <String, XKCDColor>{};
  var distance = 0;
  while (distance < 100) {
    distance++;
    var nearestRGBs = findNearestRGBs(rgb, XKCDRGBs, distance: distance);

    if (nearestRGBs.length >= 5) {
      for (var nearestRGB in nearestRGBs) {
        var nearestRAL = _xkcdByRGB(nearestRGB);
        if (nearestRAL != null) out.addAll({nearestRAL.key: nearestRAL.value});
      }
      return out;
    }
  }

  return out;
}
