part of 'package:gc_wizard/tools/symbol_tables/_common/logic/symbol_table_data.dart';

const Map<String, List<String>> _COMMON_SYMBOLS = {
  'A': ['A', '0041', 'LATIN CAPITAL LETTER A'],
  'AE': ['Æ', '00C6', 'LATIN CAPITAL LETTER AE'],
  'AEacute': ['Ǽ', '01FC', 'LATIN CAPITAL LETTER AE WITH ACUTE'],
  'Aacute': ['Á', '00C1', 'LATIN CAPITAL LETTER A WITH ACUTE'],
  'Abreve': ['Ă', '0102', 'LATIN CAPITAL LETTER A WITH BREVE'],
  'Acircumflex': ['Â', '00C2', 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX'],
  'Adieresis': ['Ä', '00C4', 'LATIN CAPITAL LETTER A WITH DIAERESIS'],
  'Agrave': ['À', '00C0', 'LATIN CAPITAL LETTER A WITH GRAVE'],
  'Alpha': ['Α', '0391', 'GREEK CAPITAL LETTER ALPHA'],
  'Alphatonos': ['Ά', '0386', 'GREEK CAPITAL LETTER ALPHA WITH TONOS'],
  'Amacron': ['Ā', '0100', 'LATIN CAPITAL LETTER A WITH MACRON'],
  'Aogonek': ['Ą', '0104', 'LATIN CAPITAL LETTER A WITH OGONEK'],
  'Aring': ['Å', '00C5', 'LATIN CAPITAL LETTER A WITH RING ABOVE'],
  'Aringacute': ['Ǻ', '01FA', 'LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE'],
  'Atilde': ['Ã', '00C3', 'LATIN CAPITAL LETTER A WITH TILDE'],
  'B': ['B', '0042', 'LATIN CAPITAL LETTER B'],
  'Beta': ['Β', '0392', 'GREEK CAPITAL LETTER BETA'],
  'C': ['C', '0043', 'LATIN CAPITAL LETTER C'],
  'Cacute': ['Ć', '0106', 'LATIN CAPITAL LETTER C WITH ACUTE'],
  'Ccaron': ['Č', '010C', 'LATIN CAPITAL LETTER C WITH CARON'],
  'Ccedilla': ['Ç', '00C7', 'LATIN CAPITAL LETTER C WITH CEDILLA'],
  'Ccircumflex': ['Ĉ', '0108', 'LATIN CAPITAL LETTER C WITH CIRCUMFLEX'],
  'Cdotaccent': ['Ċ', '010A', 'LATIN CAPITAL LETTER C WITH DOT ABOVE'],
  'Chi': ['Χ', '03A7', 'GREEK CAPITAL LETTER CHI'],
  'D': ['D', '0044', 'LATIN CAPITAL LETTER D'],
  'Dcaron': ['Ď', '010E', 'LATIN CAPITAL LETTER D WITH CARON'],
  'Dcroat': ['Đ', '0110', 'LATIN CAPITAL LETTER D WITH STROKE'],
  'Delta': ['∆', '2206', 'INCREMENT'],
  'E': ['E', '0045', 'LATIN CAPITAL LETTER E'],
  'Eacute': ['É', '00C9', 'LATIN CAPITAL LETTER E WITH ACUTE'],
  'Ebreve': ['Ĕ', '0114', 'LATIN CAPITAL LETTER E WITH BREVE'],
  'Ecaron': ['Ě', '011A', 'LATIN CAPITAL LETTER E WITH CARON'],
  'Ecircumflex': ['Ê', '00CA', 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX'],
  'Edieresis': ['Ë', '00CB', 'LATIN CAPITAL LETTER E WITH DIAERESIS'],
  'Edotaccent': ['Ė', '0116', 'LATIN CAPITAL LETTER E WITH DOT ABOVE'],
  'Egrave': ['È', '00C8', 'LATIN CAPITAL LETTER E WITH GRAVE'],
  'Emacron': ['Ē', '0112', 'LATIN CAPITAL LETTER E WITH MACRON'],
  'Eng': ['Ŋ', '014A', 'LATIN CAPITAL LETTER ENG'],
  'Eogonek': ['Ę', '0118', 'LATIN CAPITAL LETTER E WITH OGONEK'],
  'Epsilon': ['Ε', '0395', 'GREEK CAPITAL LETTER EPSILON'],
  'Epsilontonos': ['Έ', '0388', 'GREEK CAPITAL LETTER EPSILON WITH TONOS'],
  'Eta': ['Η', '0397', 'GREEK CAPITAL LETTER ETA'],
  'Etatonos': ['Ή', '0389', 'GREEK CAPITAL LETTER ETA WITH TONOS'],
  'Eth': ['Ð', '00D0', 'LATIN CAPITAL LETTER ETH'],
  'Euro': ['€', '20AC', 'EURO SIGN'],
  'F': ['F', '0046', 'LATIN CAPITAL LETTER F'],
  'G': ['G', '0047', 'LATIN CAPITAL LETTER G'],
  'Gamma': ['Γ', '0393', 'GREEK CAPITAL LETTER GAMMA'],
  'Gbreve': ['Ğ', '011E', 'LATIN CAPITAL LETTER G WITH BREVE'],
  'Gcaron': ['Ǧ', '01E6', 'LATIN CAPITAL LETTER G WITH CARON'],
  'Gcircumflex': ['Ĝ', '011C', 'LATIN CAPITAL LETTER G WITH CIRCUMFLEX'],
  'Gdotaccent': ['Ġ', '0120', 'LATIN CAPITAL LETTER G WITH DOT ABOVE'],
  'H': ['H', '0048', 'LATIN CAPITAL LETTER H'],
  'H18533': ['●', '25CF', 'BLACK CIRCLE'],
  'H18543': ['▪', '25AA', 'BLACK SMALL SQUARE'],
  'H18551': ['▫', '25AB', 'WHITE SMALL SQUARE'],
  'H22073': ['□', '25A1', 'WHITE SQUARE'],
  'Hbar': ['Ħ', '0126', 'LATIN CAPITAL LETTER H WITH STROKE'],
  'Hcircumflex': ['Ĥ', '0124', 'LATIN CAPITAL LETTER H WITH CIRCUMFLEX'],
  'I': ['I', '0049', 'LATIN CAPITAL LETTER I'],
  'IJ': ['Ĳ', '0132', 'LATIN CAPITAL LIGATURE IJ'],
  'Iacute': ['Í', '00CD', 'LATIN CAPITAL LETTER I WITH ACUTE'],
  'Ibreve': ['Ĭ', '012C', 'LATIN CAPITAL LETTER I WITH BREVE'],
  'Icircumflex': ['Î', '00CE', 'LATIN CAPITAL LETTER I WITH CIRCUMFLEX'],
  'Idieresis': ['Ï', '00CF', 'LATIN CAPITAL LETTER I WITH DIAERESIS'],
  'Idotaccent': ['İ', '0130', 'LATIN CAPITAL LETTER I WITH DOT ABOVE'],
  'Ifraktur': ['ℑ', '2111', 'BLACK-LETTER CAPITAL I'],
  'Igrave': ['Ì', '00CC', 'LATIN CAPITAL LETTER I WITH GRAVE'],
  'Imacron': ['Ī', '012A', 'LATIN CAPITAL LETTER I WITH MACRON'],
  'Iogonek': ['Į', '012E', 'LATIN CAPITAL LETTER I WITH OGONEK'],
  'Iota': ['Ι', '0399', 'GREEK CAPITAL LETTER IOTA'],
  'Iotadieresis': ['Ϊ', '03AA', 'GREEK CAPITAL LETTER IOTA WITH DIALYTIKA'],
  'Iotatonos': ['Ί', '038A', 'GREEK CAPITAL LETTER IOTA WITH TONOS'],
  'Itilde': ['Ĩ', '0128', 'LATIN CAPITAL LETTER I WITH TILDE'],
  'J': ['J', '004A', 'LATIN CAPITAL LETTER J'],
  'Jcircumflex': ['Ĵ', '0134', 'LATIN CAPITAL LETTER J WITH CIRCUMFLEX'],
  'K': ['K', '004B', 'LATIN CAPITAL LETTER K'],
  'Kappa': ['Κ', '039A', 'GREEK CAPITAL LETTER KAPPA'],
  'L': ['L', '004C', 'LATIN CAPITAL LETTER L'],
  'Lacute': ['Ĺ', '0139', 'LATIN CAPITAL LETTER L WITH ACUTE'],
  'Lambda': ['Λ', '039B', 'GREEK CAPITAL LETTER LAMDA'],
  'Lcaron': ['Ľ', '013D', 'LATIN CAPITAL LETTER L WITH CARON'],
  'Ldot': ['Ŀ', '013F', 'LATIN CAPITAL LETTER L WITH MIDDLE DOT'],
  'Lslash': ['Ł', '0141', 'LATIN CAPITAL LETTER L WITH STROKE'],
  'M': ['M', '004D', 'LATIN CAPITAL LETTER M'],
  'Mu': ['Μ', '039C', 'GREEK CAPITAL LETTER MU'],
  'N': ['N', '004E', 'LATIN CAPITAL LETTER N'],
  'Nacute': ['Ń', '0143', 'LATIN CAPITAL LETTER N WITH ACUTE'],
  'Ncaron': ['Ň', '0147', 'LATIN CAPITAL LETTER N WITH CARON'],
  'Ntilde': ['Ñ', '00D1', 'LATIN CAPITAL LETTER N WITH TILDE'],
  'Nu': ['Ν', '039D', 'GREEK CAPITAL LETTER NU'],
  'O': ['O', '004F', 'LATIN CAPITAL LETTER O'],
  'OE': ['Œ', '0152', 'LATIN CAPITAL LIGATURE OE'],
  'Oacute': ['Ó', '00D3', 'LATIN CAPITAL LETTER O WITH ACUTE'],
  'Obreve': ['Ŏ', '014E', 'LATIN CAPITAL LETTER O WITH BREVE'],
  'Ocircumflex': ['Ô', '00D4', 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX'],
  'Odieresis': ['Ö', '00D6', 'LATIN CAPITAL LETTER O WITH DIAERESIS'],
  'Ograve': ['Ò', '00D2', 'LATIN CAPITAL LETTER O WITH GRAVE'],
  'Ohorn': ['Ơ', '01A0', 'LATIN CAPITAL LETTER O WITH HORN'],
  'Ohungarumlaut': ['Ő', '0150', 'LATIN CAPITAL LETTER O WITH DOUBLE ACUTE'],
  'Omacron': ['Ō', '014C', 'LATIN CAPITAL LETTER O WITH MACRON'],
  'Omega': ['Ω', '2126', 'OHM SIGN'],
  'Omegatonos': ['Ώ', '038F', 'GREEK CAPITAL LETTER OMEGA WITH TONOS'],
  'Omicron': ['Ο', '039F', 'GREEK CAPITAL LETTER OMICRON'],
  'Omicrontonos': ['Ό', '038C', 'GREEK CAPITAL LETTER OMICRON WITH TONOS'],
  'Oslash': ['Ø', '00D8', 'LATIN CAPITAL LETTER O WITH STROKE'],
  'Oslashacute': ['Ǿ', '01FE', 'LATIN CAPITAL LETTER O WITH STROKE AND ACUTE'],
  'Otilde': ['Õ', '00D5', 'LATIN CAPITAL LETTER O WITH TILDE'],
  'P': ['P', '0050', 'LATIN CAPITAL LETTER P'],
  'Phi': ['Φ', '03A6', 'GREEK CAPITAL LETTER PHI'],
  'Pi': ['Π', '03A0', 'GREEK CAPITAL LETTER PI'],
  'Psi': ['Ψ', '03A8', 'GREEK CAPITAL LETTER PSI'],
  'Q': ['Q', '0051', 'LATIN CAPITAL LETTER Q'],
  'R': ['R', '0052', 'LATIN CAPITAL LETTER R'],
  'Racute': ['Ŕ', '0154', 'LATIN CAPITAL LETTER R WITH ACUTE'],
  'Rcaron': ['Ř', '0158', 'LATIN CAPITAL LETTER R WITH CARON'],
  'Rfraktur': ['ℜ', '211C', 'BLACK-LETTER CAPITAL R'],
  'Rho': ['Ρ', '03A1', 'GREEK CAPITAL LETTER RHO'],
  'S': ['S', '0053', 'LATIN CAPITAL LETTER S'],
  'SF010000': ['┌', '250C', 'BOX DRAWINGS LIGHT DOWN AND RIGHT'],
  'SF020000': ['└', '2514', 'BOX DRAWINGS LIGHT UP AND RIGHT'],
  'SF030000': ['┐', '2510', 'BOX DRAWINGS LIGHT DOWN AND LEFT'],
  'SF040000': ['┘', '2518', 'BOX DRAWINGS LIGHT UP AND LEFT'],
  'SF050000': ['┼', '253C', 'BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL'],
  'SF060000': ['┬', '252C', 'BOX DRAWINGS LIGHT DOWN AND HORIZONTAL'],
  'SF070000': ['┴', '2534', 'BOX DRAWINGS LIGHT UP AND HORIZONTAL'],
  'SF080000': ['├', '251C', 'BOX DRAWINGS LIGHT VERTICAL AND RIGHT'],
  'SF090000': ['┤', '2524', 'BOX DRAWINGS LIGHT VERTICAL AND LEFT'],
  'SF100000': ['─', '2500', 'BOX DRAWINGS LIGHT HORIZONTAL'],
  'SF110000': ['│', '2502', 'BOX DRAWINGS LIGHT VERTICAL'],
  'SF190000': ['╡', '2561', 'BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE'],
  'SF200000': ['╢', '2562', 'BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE'],
  'SF210000': ['╖', '2556', 'BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE'],
  'SF220000': ['╕', '2555', 'BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE'],
  'SF230000': ['╣', '2563', 'BOX DRAWINGS DOUBLE VERTICAL AND LEFT'],
  'SF240000': ['║', '2551', 'BOX DRAWINGS DOUBLE VERTICAL'],
  'SF250000': ['╗', '2557', 'BOX DRAWINGS DOUBLE DOWN AND LEFT'],
  'SF260000': ['╝', '255D', 'BOX DRAWINGS DOUBLE UP AND LEFT'],
  'SF270000': ['╜', '255C', 'BOX DRAWINGS UP DOUBLE AND LEFT SINGLE'],
  'SF280000': ['╛', '255B', 'BOX DRAWINGS UP SINGLE AND LEFT DOUBLE'],
  'SF360000': ['╞', '255E', 'BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE'],
  'SF370000': ['╟', '255F', 'BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE'],
  'SF380000': ['╚', '255A', 'BOX DRAWINGS DOUBLE UP AND RIGHT'],
  'SF390000': ['╔', '2554', 'BOX DRAWINGS DOUBLE DOWN AND RIGHT'],
  'SF400000': ['╩', '2569', 'BOX DRAWINGS DOUBLE UP AND HORIZONTAL'],
  'SF410000': ['╦', '2566', 'BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL'],
  'SF420000': ['╠', '2560', 'BOX DRAWINGS DOUBLE VERTICAL AND RIGHT'],
  'SF430000': ['═', '2550', 'BOX DRAWINGS DOUBLE HORIZONTAL'],
  'SF440000': ['╬', '256C', 'BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL'],
  'SF450000': ['╧', '2567', 'BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE'],
  'SF460000': ['╨', '2568', 'BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE'],
  'SF470000': ['╤', '2564', 'BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE'],
  'SF480000': ['╥', '2565', 'BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE'],
  'SF490000': ['╙', '2559', 'BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE'],
  'SF500000': ['╘', '2558', 'BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE'],
  'SF510000': ['╒', '2552', 'BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE'],
  'SF520000': ['╓', '2553', 'BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE'],
  'SF530000': ['╫', '256B', 'BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE'],
  'SF540000': ['╪', '256A', 'BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE'],
  'Sacute': ['Ś', '015A', 'LATIN CAPITAL LETTER S WITH ACUTE'],
  'Scaron': ['Š', '0160', 'LATIN CAPITAL LETTER S WITH CARON'],
  'Scedilla': ['Ş', '015E', 'LATIN CAPITAL LETTER S WITH CEDILLA'],
  'Scircumflex': ['Ŝ', '015C', 'LATIN CAPITAL LETTER S WITH CIRCUMFLEX'],
  'Sigma': ['Σ', '03A3', 'GREEK CAPITAL LETTER SIGMA'],
  'T': ['T', '0054', 'LATIN CAPITAL LETTER T'],
  'Tau': ['Τ', '03A4', 'GREEK CAPITAL LETTER TAU'],
  'Tbar': ['Ŧ', '0166', 'LATIN CAPITAL LETTER T WITH STROKE'],
  'Tcaron': ['Ť', '0164', 'LATIN CAPITAL LETTER T WITH CARON'],
  'Theta': ['Θ', '0398', 'GREEK CAPITAL LETTER THETA'],
  'Thorn': ['Þ', '00DE', 'LATIN CAPITAL LETTER THORN'],
  'U': ['U', '0055', 'LATIN CAPITAL LETTER U'],
  'Uacute': ['Ú', '00DA', 'LATIN CAPITAL LETTER U WITH ACUTE'],
  'Ubreve': ['Ŭ', '016C', 'LATIN CAPITAL LETTER U WITH BREVE'],
  'Ucircumflex': ['Û', '00DB', 'LATIN CAPITAL LETTER U WITH CIRCUMFLEX'],
  'Udieresis': ['Ü', '00DC', 'LATIN CAPITAL LETTER U WITH DIAERESIS'],
  'Ugrave': ['Ù', '00D9', 'LATIN CAPITAL LETTER U WITH GRAVE'],
  'Uhorn': ['Ư', '01AF', 'LATIN CAPITAL LETTER U WITH HORN'],
  'Uhungarumlaut': ['Ű', '0170', 'LATIN CAPITAL LETTER U WITH DOUBLE ACUTE'],
  'Umacron': ['Ū', '016A', 'LATIN CAPITAL LETTER U WITH MACRON'],
  'Uogonek': ['Ų', '0172', 'LATIN CAPITAL LETTER U WITH OGONEK'],
  'Upsilon': ['Υ', '03A5', 'GREEK CAPITAL LETTER UPSILON'],
  'Upsilon1': ['ϒ', '03D2', 'GREEK UPSILON WITH HOOK SYMBOL'],
  'Upsilondieresis': ['Ϋ', '03AB', 'GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA'],
  'Upsilontonos': ['Ύ', '038E', 'GREEK CAPITAL LETTER UPSILON WITH TONOS'],
  'Uring': ['Ů', '016E', 'LATIN CAPITAL LETTER U WITH RING ABOVE'],
  'Utilde': ['Ũ', '0168', 'LATIN CAPITAL LETTER U WITH TILDE'],
  'V': ['V', '0056', 'LATIN CAPITAL LETTER V'],
  'W': ['W', '0057', 'LATIN CAPITAL LETTER W'],
  'Wacute': ['Ẃ', '1E82', 'LATIN CAPITAL LETTER W WITH ACUTE'],
  'Wcircumflex': ['Ŵ', '0174', 'LATIN CAPITAL LETTER W WITH CIRCUMFLEX'],
  'Wdieresis': ['Ẅ', '1E84', 'LATIN CAPITAL LETTER W WITH DIAERESIS'],
  'Wgrave': ['Ẁ', '1E80', 'LATIN CAPITAL LETTER W WITH GRAVE'],
  'X': ['X', '0058', 'LATIN CAPITAL LETTER X'],
  'Xi': ['Ξ', '039E', 'GREEK CAPITAL LETTER XI'],
  'Y': ['Y', '0059', 'LATIN CAPITAL LETTER Y'],
  'Yacute': ['Ý', '00DD', 'LATIN CAPITAL LETTER Y WITH ACUTE'],
  'Ycircumflex': ['Ŷ', '0176', 'LATIN CAPITAL LETTER Y WITH CIRCUMFLEX'],
  'Ydieresis': ['Ÿ', '0178', 'LATIN CAPITAL LETTER Y WITH DIAERESIS'],
  'Ygrave': ['Ỳ', '1EF2', 'LATIN CAPITAL LETTER Y WITH GRAVE'],
  'Z': ['Z', '005A', 'LATIN CAPITAL LETTER Z'],
  'Zacute': ['Ź', '0179', 'LATIN CAPITAL LETTER Z WITH ACUTE'],
  'Zcaron': ['Ž', '017D', 'LATIN CAPITAL LETTER Z WITH CARON'],
  'Zdotaccent': ['Ż', '017B', 'LATIN CAPITAL LETTER Z WITH DOT ABOVE'],
  'Zeta': ['Ζ', '0396', 'GREEK CAPITAL LETTER ZETA'],
  'a': ['a', '0061', 'LATIN SMALL LETTER A'],
  'aacute': ['á', '00E1', 'LATIN SMALL LETTER A WITH ACUTE'],
  'abreve': ['ă', '0103', 'LATIN SMALL LETTER A WITH BREVE'],
  'acircumflex': ['â', '00E2', 'LATIN SMALL LETTER A WITH CIRCUMFLEX'],
  'acute': ['´', '00B4', 'ACUTE ACCENT'],
  'acutecomb': ['́', '0301', 'COMBINING ACUTE ACCENT'],
  'adieresis': ['ä', '00E4', 'LATIN SMALL LETTER A WITH DIAERESIS'],
  'ae': ['æ', '00E6', 'LATIN SMALL LETTER AE'],
  'aeacute': ['ǽ', '01FD', 'LATIN SMALL LETTER AE WITH ACUTE'],
  'agrave': ['à', '00E0', 'LATIN SMALL LETTER A WITH GRAVE'],
  'aleph': ['ℵ', '2135', 'ALEF SYMBOL'],
  'alpha': ['α', '03B1', 'GREEK SMALL LETTER ALPHA'],
  'alphatonos': ['ά', '03AC', 'GREEK SMALL LETTER ALPHA WITH TONOS'],
  'amacron': ['ā', '0101', 'LATIN SMALL LETTER A WITH MACRON'],
  'ampersand': ['&', '0026', 'AMPERSAND'],
  'angle': ['∠', '2220', 'ANGLE'],
  'angleleft': ['〈', '2329', 'LEFT-POINTING ANGLE BRACKET'],
  'angleright': ['〉', '232A', 'RIGHT-POINTING ANGLE BRACKET'],
  'anoteleia': ['·', '0387', 'GREEK ANO TELEIA'],
  'aogonek': ['ą', '0105', 'LATIN SMALL LETTER A WITH OGONEK'],
  'approxequal': ['≈', '2248', 'ALMOST EQUAL TO'],
  'aring': ['å', '00E5', 'LATIN SMALL LETTER A WITH RING ABOVE'],
  'aringacute': ['ǻ', '01FB', 'LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE'],
  'arrowboth': ['↔', '2194', 'LEFT RIGHT ARROW'],
  'arrowdblboth': ['⇔', '21D4', 'LEFT RIGHT DOUBLE ARROW'],
  'arrowdbldown': ['⇓', '21D3', 'DOWNWARDS DOUBLE ARROW'],
  'arrowdblleft': ['⇐', '21D0', 'LEFTWARDS DOUBLE ARROW'],
  'arrowdblright': ['⇒', '21D2', 'RIGHTWARDS DOUBLE ARROW'],
  'arrowdblup': ['⇑', '21D1', 'UPWARDS DOUBLE ARROW'],
  'arrowdown': ['↓', '2193', 'DOWNWARDS ARROW'],
  'arrowleft': ['←', '2190', 'LEFTWARDS ARROW'],
  'arrowright': ['→', '2192', 'RIGHTWARDS ARROW'],
  'arrowup': ['↑', '2191', 'UPWARDS ARROW'],
  'arrowupdn': ['↕', '2195', 'UP DOWN ARROW'],
  'arrowupdnbse': ['↨', '21A8', 'UP DOWN ARROW WITH BASE'],
  'asciicircum': ['^', '005E', 'CIRCUMFLEX ACCENT'],
  'asciitilde': ['~', '007E', 'TILDE'],
  'asterisk': ['*', '002A', 'ASTERISK'],
  'asteriskmath': ['∗', '2217', 'ASTERISK OPERATOR'],
  'at': ['@', '0040', 'COMMERCIAL AT'],
  'atilde': ['ã', '00E3', 'LATIN SMALL LETTER A WITH TILDE'],
  'b': ['b', '0062', 'LATIN SMALL LETTER B'],
  'backslash': ['\\', '005C', 'REVERSE SOLIDUS'],
  'bar': ['|', '007C', 'VERTICAL LINE'],
  'beta': ['β', '03B2', 'GREEK SMALL LETTER BETA'],
  'block': ['█', '2588', 'FULL BLOCK'],
  'braceleft': ['{', '007B', 'LEFT CURLY BRACKET'],
  'braceright': ['}', '007D', 'RIGHT CURLY BRACKET'],
  'bracketleft': ['[', '005B', 'LEFT SQUARE BRACKET'],
  'bracketright': [']', '005D', 'RIGHT SQUARE BRACKET'],
  'breve': ['˘', '02D8', 'BREVE'],
  'brokenbar': ['¦', '00A6', 'BROKEN BAR'],
  'bullet': ['•', '2022', 'BULLET'],
  'c': ['c', '0063', 'LATIN SMALL LETTER C'],
  'cacute': ['ć', '0107', 'LATIN SMALL LETTER C WITH ACUTE'],
  'caron': ['ˇ', '02C7', 'CARON'],
  'carriagereturn': ['↵', '21B5', 'DOWNWARDS ARROW WITH CORNER LEFTWARDS'],
  'ccaron': ['č', '010D', 'LATIN SMALL LETTER C WITH CARON'],
  'ccedilla': ['ç', '00E7', 'LATIN SMALL LETTER C WITH CEDILLA'],
  'ccircumflex': ['ĉ', '0109', 'LATIN SMALL LETTER C WITH CIRCUMFLEX'],
  'cdotaccent': ['ċ', '010B', 'LATIN SMALL LETTER C WITH DOT ABOVE'],
  'cedilla': ['¸', '00B8', 'CEDILLA'],
  'cent': ['¢', '00A2', 'CENT SIGN'],
  'chi': ['χ', '03C7', 'GREEK SMALL LETTER CHI'],
  'circle': ['○', '25CB', 'WHITE CIRCLE'],
  'circlemultiply': ['⊗', '2297', 'CIRCLED TIMES'],
  'circleplus': ['⊕', '2295', 'CIRCLED PLUS'],
  'circumflex': ['ˆ', '02C6', 'MODIFIER LETTER CIRCUMFLEX ACCENT'],
  'club': ['♣', '2663', 'BLACK CLUB SUIT'],
  'colon': [':', '003A', 'COLON'],
  'colonmonetary': ['₡', '20A1', 'COLON SIGN'],
  'comma': [',', '002C', 'COMMA'],
  'congruent': ['≅', '2245', 'APPROXIMATELY EQUAL TO'],
  'copyright': ['©', '00A9', 'COPYRIGHT SIGN'],
  'currency': ['¤', '00A4', 'CURRENCY SIGN'],
  'd': ['d', '0064', 'LATIN SMALL LETTER D'],
  'dagger': ['†', '2020', 'DAGGER'],
  'daggerdbl': ['‡', '2021', 'DOUBLE DAGGER'],
  'dcaron': ['ď', '010F', 'LATIN SMALL LETTER D WITH CARON'],
  'dcroat': ['đ', '0111', 'LATIN SMALL LETTER D WITH STROKE'],
  'degree': ['°', '00B0', 'DEGREE SIGN'],
  'delta': ['δ', '03B4', 'GREEK SMALL LETTER DELTA'],
  'diamond': ['♦', '2666', 'BLACK DIAMOND SUIT'],
  'dieresis': ['¨', '00A8', 'DIAERESIS'],
  'dieresistonos': ['΅', '0385', 'GREEK DIALYTIKA TONOS'],
  'divide': ['÷', '00F7', 'DIVISION SIGN'],
  'dkshade': ['▓', '2593', 'DARK SHADE'],
  'dnblock': ['▄', '2584', 'LOWER HALF BLOCK'],
  'dollar': ['\$', '0024', 'DOLLAR SIGN'],
  'dong': ['₫', '20AB', 'DONG SIGN'],
  'dotaccent': ['˙', '02D9', 'DOT ABOVE'],
  'dotbelowcomb': ['̣', '0323', 'COMBINING DOT BELOW'],
  'dotlessi': ['ı', '0131', 'LATIN SMALL LETTER DOTLESS I'],
  'dotmath': ['⋅', '22C5', 'DOT OPERATOR'],
  'e': ['e', '0065', 'LATIN SMALL LETTER E'],
  'eacute': ['é', '00E9', 'LATIN SMALL LETTER E WITH ACUTE'],
  'ebreve': ['ĕ', '0115', 'LATIN SMALL LETTER E WITH BREVE'],
  'ecaron': ['ě', '011B', 'LATIN SMALL LETTER E WITH CARON'],
  'ecircumflex': ['ê', '00EA', 'LATIN SMALL LETTER E WITH CIRCUMFLEX'],
  'edieresis': ['ë', '00EB', 'LATIN SMALL LETTER E WITH DIAERESIS'],
  'edotaccent': ['ė', '0117', 'LATIN SMALL LETTER E WITH DOT ABOVE'],
  'egrave': ['è', '00E8', 'LATIN SMALL LETTER E WITH GRAVE'],
  'eight': ['8', '0038', 'DIGIT EIGHT'],
  'element': ['∈', '2208', 'ELEMENT OF'],
  'ellipsis': ['…', '2026', 'HORIZONTAL ELLIPSIS'],
  'emacron': ['ē', '0113', 'LATIN SMALL LETTER E WITH MACRON'],
  'emdash': ['—', '2014', 'EM DASH'],
  'emptyset': ['∅', '2205', 'EMPTY SET'],
  'endash': ['–', '2013', 'EN DASH'],
  'eng': ['ŋ', '014B', 'LATIN SMALL LETTER ENG'],
  'eogonek': ['ę', '0119', 'LATIN SMALL LETTER E WITH OGONEK'],
  'epsilon': ['ε', '03B5', 'GREEK SMALL LETTER EPSILON'],
  'epsilontonos': ['έ', '03AD', 'GREEK SMALL LETTER EPSILON WITH TONOS'],
  'equal': ['=', '003D', 'EQUALS SIGN'],
  'equivalence': ['≡', '2261', 'IDENTICAL TO'],
  'estimated': ['℮', '212E', 'ESTIMATED SYMBOL'],
  'eta': ['η', '03B7', 'GREEK SMALL LETTER ETA'],
  'etatonos': ['ή', '03AE', 'GREEK SMALL LETTER ETA WITH TONOS'],
  'eth': ['ð', '00F0', 'LATIN SMALL LETTER ETH'],
  'exclam': ['!', '0021', 'EXCLAMATION MARK'],
  'exclamdbl': ['‼', '203C', 'DOUBLE EXCLAMATION MARK'],
  'exclamdown': ['¡', '00A1', 'INVERTED EXCLAMATION MARK'],
  'existential': ['∃', '2203', 'THERE EXISTS'],
  'f': ['f', '0066', 'LATIN SMALL LETTER F'],
  'female': ['♀', '2640', 'FEMALE SIGN'],
  'figuredash': ['‒', '2012', 'FIGURE DASH'],
  'filledbox': ['■', '25A0', 'BLACK SQUARE'],
  'filledrect': ['▬', '25AC', 'BLACK RECTANGLE'],
  'five': ['5', '0035', 'DIGIT FIVE'],
  'fiveeighths': ['⅝', '215D', 'VULGAR FRACTION FIVE EIGHTHS'],
  'florin': ['ƒ', '0192', 'LATIN SMALL LETTER F WITH HOOK'],
  'four': ['4', '0034', 'DIGIT FOUR'],
  'fraction': ['⁄', '2044', 'FRACTION SLASH'],
  'franc': ['₣', '20A3', 'FRENCH FRANC SIGN'],
  'g': ['g', '0067', 'LATIN SMALL LETTER G'],
  'gamma': ['γ', '03B3', 'GREEK SMALL LETTER GAMMA'],
  'gbreve': ['ğ', '011F', 'LATIN SMALL LETTER G WITH BREVE'],
  'gcaron': ['ǧ', '01E7', 'LATIN SMALL LETTER G WITH CARON'],
  'gcircumflex': ['ĝ', '011D', 'LATIN SMALL LETTER G WITH CIRCUMFLEX'],
  'gdotaccent': ['ġ', '0121', 'LATIN SMALL LETTER G WITH DOT ABOVE'],
  'germandbls': ['ß', '00DF', 'LATIN SMALL LETTER SHARP S'],
  'gradient': ['∇', '2207', 'NABLA'],
  'grave': ['`', '0060', 'GRAVE ACCENT'],
  'gravecomb': ['̀', '0300', 'COMBINING GRAVE ACCENT'],
  'greater': ['>', '003E', 'GREATER-THAN SIGN'],
  'greaterequal': ['≥', '2265', 'GREATER-THAN OR EQUAL TO'],
  'guillemotleft': ['«', '00AB', 'LEFT-POINTING DOUBLE ANGLE QUOTATION MARK'],
  'guillemotright': ['»', '00BB', 'RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK'],
  'guilsinglleft': ['‹', '2039', 'SINGLE LEFT-POINTING ANGLE QUOTATION MARK'],
  'guilsinglright': ['›', '203A', 'SINGLE RIGHT-POINTING ANGLE QUOTATION MARK'],
  'h': ['h', '0068', 'LATIN SMALL LETTER H'],
  'hbar': ['ħ', '0127', 'LATIN SMALL LETTER H WITH STROKE'],
  'hcircumflex': ['ĥ', '0125', 'LATIN SMALL LETTER H WITH CIRCUMFLEX'],
  'heart': ['♥', '2665', 'BLACK HEART SUIT'],
  'hookabovecomb': ['̉', '0309', 'COMBINING HOOK ABOVE'],
  'house': ['⌂', '2302', 'HOUSE'],
  'hungarumlaut': ['˝', '02DD', 'DOUBLE ACUTE ACCENT'],
  'hyphen': ['-', '002D', 'HYPHEN-MINUS'],
  'i': ['i', '0069', 'LATIN SMALL LETTER I'],
  'iacute': ['í', '00ED', 'LATIN SMALL LETTER I WITH ACUTE'],
  'ibreve': ['ĭ', '012D', 'LATIN SMALL LETTER I WITH BREVE'],
  'icircumflex': ['î', '00EE', 'LATIN SMALL LETTER I WITH CIRCUMFLEX'],
  'idieresis': ['ï', '00EF', 'LATIN SMALL LETTER I WITH DIAERESIS'],
  'igrave': ['ì', '00EC', 'LATIN SMALL LETTER I WITH GRAVE'],
  'ij': ['ĳ', '0133', 'LATIN SMALL LIGATURE IJ'],
  'imacron': ['ī', '012B', 'LATIN SMALL LETTER I WITH MACRON'],
  'infinity': ['∞', '221E', 'INFINITY'],
  'integral': ['∫', '222B', 'INTEGRAL'],
  'integralbt': ['⌡', '2321', 'BOTTOM HALF INTEGRAL'],
  'integraltp': ['⌠', '2320', 'TOP HALF INTEGRAL'],
  'intersection': ['∩', '2229', 'INTERSECTION'],
  'invbullet': ['◘', '25D8', 'INVERSE BULLET'],
  'invcircle': ['◙', '25D9', 'INVERSE WHITE CIRCLE'],
  'invsmileface': ['☻', '263B', 'BLACK SMILING FACE'],
  'iogonek': ['į', '012F', 'LATIN SMALL LETTER I WITH OGONEK'],
  'iota': ['ι', '03B9', 'GREEK SMALL LETTER IOTA'],
  'iotadieresis': ['ϊ', '03CA', 'GREEK SMALL LETTER IOTA WITH DIALYTIKA'],
  'iotadieresistonos': ['ΐ', '0390', 'GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS'],
  'iotatonos': ['ί', '03AF', 'GREEK SMALL LETTER IOTA WITH TONOS'],
  'itilde': ['ĩ', '0129', 'LATIN SMALL LETTER I WITH TILDE'],
  'j': ['j', '006A', 'LATIN SMALL LETTER J'],
  'jcircumflex': ['ĵ', '0135', 'LATIN SMALL LETTER J WITH CIRCUMFLEX'],
  'k': ['k', '006B', 'LATIN SMALL LETTER K'],
  'kappa': ['κ', '03BA', 'GREEK SMALL LETTER KAPPA'],
  'kgreenlandic': ['ĸ', '0138', 'LATIN SMALL LETTER KRA'],
  'l': ['l', '006C', 'LATIN SMALL LETTER L'],
  'lacute': ['ĺ', '013A', 'LATIN SMALL LETTER L WITH ACUTE'],
  'lambda': ['λ', '03BB', 'GREEK SMALL LETTER LAMDA'],
  'lcaron': ['ľ', '013E', 'LATIN SMALL LETTER L WITH CARON'],
  'ldot': ['ŀ', '0140', 'LATIN SMALL LETTER L WITH MIDDLE DOT'],
  'less': ['<', '003C', 'LESS-THAN SIGN'],
  'lessequal': ['≤', '2264', 'LESS-THAN OR EQUAL TO'],
  'lfblock': ['▌', '258C', 'LEFT HALF BLOCK'],
  'lira': ['₤', '20A4', 'LIRA SIGN'],
  'logicaland': ['∧', '2227', 'LOGICAL AND'],
  'logicalnot': ['¬', '00AC', 'NOT SIGN'],
  'logicalor': ['∨', '2228', 'LOGICAL OR'],
  'longs': ['ſ', '017F', 'LATIN SMALL LETTER LONG S'],
  'lozenge': ['◊', '25CA', 'LOZENGE'],
  'lslash': ['ł', '0142', 'LATIN SMALL LETTER L WITH STROKE'],
  'ltshade': ['░', '2591', 'LIGHT SHADE'],
  'm': ['m', '006D', 'LATIN SMALL LETTER M'],
  'macron': ['¯', '00AF', 'MACRON'],
  'male': ['♂', '2642', 'MALE SIGN'],
  'minus': ['−', '2212', 'MINUS SIGN'],
  'minute': ['′', '2032', 'PRIME'],
  'mu': ['µ', '00B5', 'MICRO SIGN'],
  'multiply': ['×', '00D7', 'MULTIPLICATION SIGN'],
  'musicalnote': ['♪', '266A', 'EIGHTH NOTE'],
  'musicalnotedbl': ['♫', '266B', 'BEAMED EIGHTH NOTES'],
  'n': ['n', '006E', 'LATIN SMALL LETTER N'],
  'nacute': ['ń', '0144', 'LATIN SMALL LETTER N WITH ACUTE'],
  'napostrophe': ['ŉ', '0149', 'LATIN SMALL LETTER N PRECEDED BY APOSTROPHE'],
  'ncaron': ['ň', '0148', 'LATIN SMALL LETTER N WITH CARON'],
  'nine': ['9', '0039', 'DIGIT NINE'],
  'notelement': ['∉', '2209', 'NOT AN ELEMENT OF'],
  'notequal': ['≠', '2260', 'NOT EQUAL TO'],
  'notsubset': ['⊄', '2284', 'NOT A SUBSET OF'],
  'ntilde': ['ñ', '00F1', 'LATIN SMALL LETTER N WITH TILDE'],
  'nu': ['ν', '03BD', 'GREEK SMALL LETTER NU'],
  'numbersign': ['#', '0023', 'NUMBER SIGN'],
  'o': ['o', '006F', 'LATIN SMALL LETTER O'],
  'oacute': ['ó', '00F3', 'LATIN SMALL LETTER O WITH ACUTE'],
  'obreve': ['ŏ', '014F', 'LATIN SMALL LETTER O WITH BREVE'],
  'ocircumflex': ['ô', '00F4', 'LATIN SMALL LETTER O WITH CIRCUMFLEX'],
  'odieresis': ['ö', '00F6', 'LATIN SMALL LETTER O WITH DIAERESIS'],
  'oe': ['œ', '0153', 'LATIN SMALL LIGATURE OE'],
  'ogonek': ['˛', '02DB', 'OGONEK'],
  'ograve': ['ò', '00F2', 'LATIN SMALL LETTER O WITH GRAVE'],
  'ohorn': ['ơ', '01A1', 'LATIN SMALL LETTER O WITH HORN'],
  'ohungarumlaut': ['ő', '0151', 'LATIN SMALL LETTER O WITH DOUBLE ACUTE'],
  'omacron': ['ō', '014D', 'LATIN SMALL LETTER O WITH MACRON'],
  'omega': ['ω', '03C9', 'GREEK SMALL LETTER OMEGA'],
  'omega1': ['ϖ', '03D6', 'GREEK PI SYMBOL'],
  'omegatonos': ['ώ', '03CE', 'GREEK SMALL LETTER OMEGA WITH TONOS'],
  'omicron': ['ο', '03BF', 'GREEK SMALL LETTER OMICRON'],
  'omicrontonos': ['ό', '03CC', 'GREEK SMALL LETTER OMICRON WITH TONOS'],
  'one': ['1', '0031', 'DIGIT ONE'],
  'onedotenleader': ['․', '2024', 'ONE DOT LEADER'],
  'oneeighth': ['⅛', '215B', 'VULGAR FRACTION ONE EIGHTH'],
  'onehalf': ['½', '00BD', 'VULGAR FRACTION ONE HALF'],
  'onequarter': ['¼', '00BC', 'VULGAR FRACTION ONE QUARTER'],
  'onethird': ['⅓', '2153', 'VULGAR FRACTION ONE THIRD'],
  'openbullet': ['◦', '25E6', 'WHITE BULLET'],
  'ordfeminine': ['ª', '00AA', 'FEMININE ORDINAL INDICATOR'],
  'ordmasculine': ['º', '00BA', 'MASCULINE ORDINAL INDICATOR'],
  'orthogonal': ['∟', '221F', 'RIGHT ANGLE'],
  'oslash': ['ø', '00F8', 'LATIN SMALL LETTER O WITH STROKE'],
  'oslashacute': ['ǿ', '01FF', 'LATIN SMALL LETTER O WITH STROKE AND ACUTE'],
  'otilde': ['õ', '00F5', 'LATIN SMALL LETTER O WITH TILDE'],
  'p': ['p', '0070', 'LATIN SMALL LETTER P'],
  'paragraph': ['¶', '00B6', 'PILCROW SIGN'],
  'parenleft': ['(', '0028', 'LEFT PARENTHESIS'],
  'parenright': [')', '0029', 'RIGHT PARENTHESIS'],
  'partialdiff': ['∂', '2202', 'PARTIAL DIFFERENTIAL'],
  'percent': ['%', '0025', 'PERCENT SIGN'],
  'period': ['.', '002E', 'FULL STOP'],
  'periodcentered': ['·', '00B7', 'MIDDLE DOT'],
  'perpendicular': ['⊥', '22A5', 'UP TACK'],
  'perthousand': ['‰', '2030', 'PER MILLE SIGN'],
  'peseta': ['₧', '20A7', 'PESETA SIGN'],
  'phi': ['φ', '03C6', 'GREEK SMALL LETTER PHI'],
  'phi1': ['ϕ', '03D5', 'GREEK PHI SYMBOL'],
  'pi': ['π', '03C0', 'GREEK SMALL LETTER PI'],
  'plus': ['+', '002B', 'PLUS SIGN'],
  'plusminus': ['±', '00B1', 'PLUS-MINUS SIGN'],
  'prescription': ['℞', '211E', 'PRESCRIPTION TAKE'],
  'product': ['∏', '220F', 'N-ARY PRODUCT'],
  'propersubset': ['⊂', '2282', 'SUBSET OF'],
  'propersuperset': ['⊃', '2283', 'SUPERSET OF'],
  'proportional': ['∝', '221D', 'PROPORTIONAL TO'],
  'psi': ['ψ', '03C8', 'GREEK SMALL LETTER PSI'],
  'q': ['q', '0071', 'LATIN SMALL LETTER Q'],
  'question': ['?', '003F', 'QUESTION MARK'],
  'questiondown': ['¿', '00BF', 'INVERTED QUESTION MARK'],
  'quotedbl': ['"', '0022', 'QUOTATION MARK'],
  'quotedblbase': ['„', '201E', 'DOUBLE LOW-9 QUOTATION MARK'],
  'quotedblleft': ['“', '201C', 'LEFT DOUBLE QUOTATION MARK'],
  'quotedblright': ['”', '201D', 'RIGHT DOUBLE QUOTATION MARK'],
  'quoteleft': ['‘', '2018', 'LEFT SINGLE QUOTATION MARK'],
  'quotereversed': ['‛', '201B', 'SINGLE HIGH-REVERSED-9 QUOTATION MARK'],
  'quoteright': ['’', '2019', 'RIGHT SINGLE QUOTATION MARK'],
  'quotesinglbase': ['‚', '201A', 'SINGLE LOW-9 QUOTATION MARK'],
  'quotesingle': ['\'', '0027', 'APOSTROPHE'],
  'r': ['r', '0072', 'LATIN SMALL LETTER R'],
  'racute': ['ŕ', '0155', 'LATIN SMALL LETTER R WITH ACUTE'],
  'radical': ['√', '221A', 'SQUARE ROOT'],
  'rcaron': ['ř', '0159', 'LATIN SMALL LETTER R WITH CARON'],
  'reflexsubset': ['⊆', '2286', 'SUBSET OF OR EQUAL TO'],
  'reflexsuperset': ['⊇', '2287', 'SUPERSET OF OR EQUAL TO'],
  'registered': ['®', '00AE', 'REGISTERED SIGN'],
  'revlogicalnot': ['⌐', '2310', 'REVERSED NOT SIGN'],
  'rho': ['ρ', '03C1', 'GREEK SMALL LETTER RHO'],
  'ring': ['˚', '02DA', 'RING ABOVE'],
  'rtblock': ['▐', '2590', 'RIGHT HALF BLOCK'],
  's': ['s', '0073', 'LATIN SMALL LETTER S'],
  'sacute': ['ś', '015B', 'LATIN SMALL LETTER S WITH ACUTE'],
  'scaron': ['š', '0161', 'LATIN SMALL LETTER S WITH CARON'],
  'scedilla': ['ş', '015F', 'LATIN SMALL LETTER S WITH CEDILLA'],
  'scircumflex': ['ŝ', '015D', 'LATIN SMALL LETTER S WITH CIRCUMFLEX'],
  'second': ['″', '2033', 'DOUBLE PRIME'],
  'section': ['§', '00A7', 'SECTION SIGN'],
  'semicolon': [';', '003B', 'SEMICOLON'],
  'seven': ['7', '0037', 'DIGIT SEVEN'],
  'seveneighths': ['⅞', '215E', 'VULGAR FRACTION SEVEN EIGHTHS'],
  'shade': ['▒', '2592', 'MEDIUM SHADE'],
  'sigma': ['σ', '03C3', 'GREEK SMALL LETTER SIGMA'],
  'sigma1': ['ς', '03C2', 'GREEK SMALL LETTER FINAL SIGMA'],
  'similar': ['∼', '223C', 'TILDE OPERATOR'],
  'six': ['6', '0036', 'DIGIT SIX'],
  'slash': ['/', '002F', 'SOLIDUS'],
  'smileface': ['☺', '263A', 'WHITE SMILING FACE'],
  'space': [' ', '0020', 'SPACE'],
  'spade': ['♠', '2660', 'BLACK SPADE SUIT'],
  'sterling': ['£', '00A3', 'POUND SIGN'],
  'suchthat': ['∋', '220B', 'CONTAINS AS MEMBER'],
  'summation': ['∑', '2211', 'N-ARY SUMMATION'],
  'sun': ['☼', '263C', 'WHITE SUN WITH RAYS'],
  't': ['t', '0074', 'LATIN SMALL LETTER T'],
  'tau': ['τ', '03C4', 'GREEK SMALL LETTER TAU'],
  'tbar': ['ŧ', '0167', 'LATIN SMALL LETTER T WITH STROKE'],
  'tcaron': ['ť', '0165', 'LATIN SMALL LETTER T WITH CARON'],
  'therefore': ['∴', '2234', 'THEREFORE'],
  'theta': ['θ', '03B8', 'GREEK SMALL LETTER THETA'],
  'theta1': ['ϑ', '03D1', 'GREEK THETA SYMBOL'],
  'thorn': ['þ', '00FE', 'LATIN SMALL LETTER THORN'],
  'three': ['3', '0033', 'DIGIT THREE'],
  'threeeighths': ['⅜', '215C', 'VULGAR FRACTION THREE EIGHTHS'],
  'threequarters': ['¾', '00BE', 'VULGAR FRACTION THREE QUARTERS'],
  'tilde': ['˜', '02DC', 'SMALL TILDE'],
  'tildecomb': ['̃', '0303', 'COMBINING TILDE'],
  'tonos': ['΄', '0384', 'GREEK TONOS'],
  'trademark': ['™', '2122', 'TRADE MARK SIGN'],
  'triagdn': ['▼', '25BC', 'BLACK DOWN-POINTING TRIANGLE'],
  'triaglf': ['◄', '25C4', 'BLACK LEFT-POINTING POINTER'],
  'triagrt': ['►', '25BA', 'BLACK RIGHT-POINTING POINTER'],
  'triagup': ['▲', '25B2', 'BLACK UP-POINTING TRIANGLE'],
  'two': ['2', '0032', 'DIGIT TWO'],
  'twodotenleader': ['‥', '2025', 'TWO DOT LEADER'],
  'twothirds': ['⅔', '2154', 'VULGAR FRACTION TWO THIRDS'],
  'u': ['u', '0075', 'LATIN SMALL LETTER U'],
  'uacute': ['ú', '00FA', 'LATIN SMALL LETTER U WITH ACUTE'],
  'ubreve': ['ŭ', '016D', 'LATIN SMALL LETTER U WITH BREVE'],
  'ucircumflex': ['û', '00FB', 'LATIN SMALL LETTER U WITH CIRCUMFLEX'],
  'udieresis': ['ü', '00FC', 'LATIN SMALL LETTER U WITH DIAERESIS'],
  'ugrave': ['ù', '00F9', 'LATIN SMALL LETTER U WITH GRAVE'],
  'uhorn': ['ư', '01B0', 'LATIN SMALL LETTER U WITH HORN'],
  'uhungarumlaut': ['ű', '0171', 'LATIN SMALL LETTER U WITH DOUBLE ACUTE'],
  'umacron': ['ū', '016B', 'LATIN SMALL LETTER U WITH MACRON'],
  'underscore': ['_', '005F', 'LOW LINE'],
  'underscoredbl': ['‗', '2017', 'DOUBLE LOW LINE'],
  'union': ['∪', '222A', 'UNION'],
  'universal': ['∀', '2200', 'FOR ALL'],
  'uogonek': ['ų', '0173', 'LATIN SMALL LETTER U WITH OGONEK'],
  'upblock': ['▀', '2580', 'UPPER HALF BLOCK'],
  'upsilon': ['υ', '03C5', 'GREEK SMALL LETTER UPSILON'],
  'upsilondieresis': ['ϋ', '03CB', 'GREEK SMALL LETTER UPSILON WITH DIALYTIKA'],
  'upsilondieresistonos': ['ΰ', '03B0', 'GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS'],
  'upsilontonos': ['ύ', '03CD', 'GREEK SMALL LETTER UPSILON WITH TONOS'],
  'uring': ['ů', '016F', 'LATIN SMALL LETTER U WITH RING ABOVE'],
  'utilde': ['ũ', '0169', 'LATIN SMALL LETTER U WITH TILDE'],
  'v': ['v', '0076', 'LATIN SMALL LETTER V'],
  'w': ['w', '0077', 'LATIN SMALL LETTER W'],
  'wacute': ['ẃ', '1E83', 'LATIN SMALL LETTER W WITH ACUTE'],
  'wcircumflex': ['ŵ', '0175', 'LATIN SMALL LETTER W WITH CIRCUMFLEX'],
  'wdieresis': ['ẅ', '1E85', 'LATIN SMALL LETTER W WITH DIAERESIS'],
  'weierstrass': ['℘', '2118', 'SCRIPT CAPITAL P'],
  'wgrave': ['ẁ', '1E81', 'LATIN SMALL LETTER W WITH GRAVE'],
  'x': ['x', '0078', 'LATIN SMALL LETTER X'],
  'xi': ['ξ', '03BE', 'GREEK SMALL LETTER XI'],
  'y': ['y', '0079', 'LATIN SMALL LETTER Y'],
  'yacute': ['ý', '00FD', 'LATIN SMALL LETTER Y WITH ACUTE'],
  'ycircumflex': ['ŷ', '0177', 'LATIN SMALL LETTER Y WITH CIRCUMFLEX'],
  'ydieresis': ['ÿ', '00FF', 'LATIN SMALL LETTER Y WITH DIAERESIS'],
  'yen': ['¥', '00A5', 'YEN SIGN'],
  'ygrave': ['ỳ', '1EF3', 'LATIN SMALL LETTER Y WITH GRAVE'],
  'z': ['z', '007A', 'LATIN SMALL LETTER Z'],
  'zacute': ['ź', '017A', 'LATIN SMALL LETTER Z WITH ACUTE'],
  'zcaron': ['ž', '017E', 'LATIN SMALL LETTER Z WITH CARON'],
  'zdotaccent': ['ż', '017C', 'LATIN SMALL LETTER Z WITH DOT ABOVE'],
  'zero': ['0', '0030', 'DIGIT ZERO'],
  'zeta': ['ζ', '03B6', 'GREEK SMALL LETTER ZETA'],
  // additions - not standard
  'combiningmacron': [' ̄', '0304', 'COMBINING MACRON'],
  'combiningcedilla': [' ̧', '0304', 'COMBINING CEDILLA'],
  'Yr': ['Ʀ', '01A6', 'LATIN LETTER YR'],
  'yr': ['ʀ', '0280', 'LATIN LETTER SMALL CAPITAL R'],
  'Yogh': ['Ȝ', '021C', 'LATIN CAPITAL LETTER YOGH'],
  'Ddotbelow': ['Ḍ', '1E0C', 'LATIN CAPITAL LETTER D WITH DOT BELOW'],
  'Hdotbelow': ['Ḥ', '1E24', 'LATIN CAPITAL LETTER H WITH DOT BELOW'],
  'Rdotbelow': ['Ṛ', '1E5A', 'LATIN CAPITAL LETTER R WITH DOT BELOW'],
  'Sdotbelow': ['Ṣ', '1E62', 'LATIN CAPITAL LETTER S WITH DOT BELOW'],
  'Tdotbelow': ['Ṭ', '1E6C', 'LATIN CAPITAL LETTER T WITH DOT BELOW'],
  'Zdotbelow': ['Ẓ', '1E92', 'LATIN CAPITAL LETTER Z WITH DOT BELOW'],
  'ddotbelow': ['ḍ', '1E0D', 'LATIN SMALL LETTER D WITH DOT BELOW'],
  'hdotbelow': ['ḥ', '1E25', 'LATIN SMALL LETTER H WITH DOT BELOW'],
  'rdotbelow': ['ṛ', '1E5B', 'LATIN SMALL LETTER R WITH DOT BELOW'],
  'sdotbelow': ['ṣ', '1E63', 'LATIN SMALL LETTER S WITH DOT BELOW'],
  'tdotbelow': ['ṭ', '1E6D', 'LATIN SMALL LETTER T WITH DOT BELOW'],
  'zdotbelow': ['ẓ', '1E93', 'LATIN SMALL LETTER Z WITH DOT BELOW'],
  'superscriptzero': ['⁰', '2070', 'SUPERSCRIPT ZERO'],
  'superscriptone': ['¹', '00B9', 'SUPERSCRIPT ONE'],
  'superscripttwo': ['²', '00B2', 'SUPERSCRIPT TWO'],
  'superscriptthree': ['³', '00B3', 'SUPERSCRIPT THREE'],
  'dje': ['ђ', '0452', 'CYRILLIC SMALL LETTER DJE'],
  'Dje': ['Ђ', '0402', 'CYRILLIC CAPITAL LETTER DJE'],
};